// Generated by declarative-openapi. Do not edit.

import DeclarativeRequests
import Foundation

// The whole backend in one closed type — sections mirror the OpenAPI document.
enum RedoclyMuseumAPI {
    // MARK: - Schemas (components.schemas)

    typealias APIDate = String

    struct APIError: Codable {
        var title: String? = nil
        var type: String? = nil
    }

    struct BuyMuseumTickets: Codable {
        var email: Email? = nil
        var eventId: EventId? = nil
        var ticketDate: APIDate
        var ticketId: TicketId? = nil
        var ticketType: TicketType
    }

    typealias Email = String

    typealias EventDates = [APIDate]

    typealias EventDescription = String

    typealias EventId = String

    typealias EventLocation = String

    typealias EventName = String

    typealias EventPrice = Double

    struct MuseumDailyHours: Codable {
        var date: APIDate
        var timeClose: String
        var timeOpen: String
    }

    typealias MuseumHours = [MuseumDailyHours]

    struct MuseumTicketsConfirmation: Codable {
        var confirmationCode: TicketConfirmation
        var eventId: EventId? = nil
        var message: TicketMessage
        var ticketDate: APIDate
        var ticketId: TicketId? = nil
        var ticketType: TicketType
    }

    struct SpecialEvent: Codable {
        var dates: EventDates
        var eventDescription: EventDescription
        var eventId: EventId? = nil
        var location: EventLocation
        var name: EventName
        var price: EventPrice
    }

    typealias SpecialEventCollection = [SpecialEvent]

    struct SpecialEventFields: Codable {
        var dates: EventDates? = nil
        var eventDescription: EventDescription? = nil
        var location: EventLocation? = nil
        var name: EventName? = nil
        var price: EventPrice? = nil
    }

    struct Ticket: Codable {
        var eventId: EventId? = nil
        var ticketDate: APIDate
        var ticketId: TicketId? = nil
        var ticketType: TicketType
    }

    typealias TicketCodeImage = Data

    typealias TicketConfirmation = String

    typealias TicketId = String

    typealias TicketMessage = String

    enum TicketType: String, Codable {
        case event
        case general
    }

    // MARK: - Operations (paths)

    // each operation IS a block
    enum Operation: RequestBuildable {
        case getMuseumHours(startDate: String?, page: Int?, limit: Int?)
        case listSpecialEvents(startDate: String?, endDate: String?, page: Int?, limit: Int?)
        case createSpecialEvent(body: SpecialEvent)
        case getSpecialEvent(eventId: String)
        case updateSpecialEvent(eventId: String, body: SpecialEventFields)
        case deleteSpecialEvent(eventId: String)
        case buyMuseumTickets(body: BuyMuseumTickets)
        case getTicketCode(ticketId: String)

        var body: some RequestBuildable {
            switch self {
            case let .getMuseumHours(startDate, page, limit):
                Method.GET
                Endpoint("museum-hours")
                if let startDate {
                    Query("startDate", startDate)
                }
                if let page {
                    Query("page", String(page))
                }
                if let limit {
                    Query("limit", String(limit))
                }
            case let .listSpecialEvents(startDate, endDate, page, limit):
                Method.GET
                Endpoint("special-events")
                if let startDate {
                    Query("startDate", startDate)
                }
                if let endDate {
                    Query("endDate", endDate)
                }
                if let page {
                    Query("page", String(page))
                }
                if let limit {
                    Query("limit", String(limit))
                }
            case let .createSpecialEvent(body):
                Method.POST
                Endpoint("special-events")
                RequestBody.json(body)
            case let .getSpecialEvent(eventId):
                Method.GET
                Endpoint("special-events/\(eventId)")
            case let .updateSpecialEvent(eventId, body):
                Method.PATCH
                Endpoint("special-events/\(eventId)")
                RequestBody.json(body)
            case let .deleteSpecialEvent(eventId):
                Method.DELETE
                Endpoint("special-events/\(eventId)")
            case let .buyMuseumTickets(body):
                Method.POST
                Endpoint("tickets")
                RequestBody.json(body)
            case let .getTicketCode(ticketId):
                Method.GET
                Endpoint("tickets/\(ticketId)/qr")
            }
        }
    }

    // MARK: - Responses (responses)

    /// One error, nothing lost: payload and the raw response —
    /// decode the spec's error model from `data` in the layer that needs it.
    struct ResponseError: Error {
        let operation: Operation
        let data: Data
        let response: URLResponse

        /// Projection, not storage: nil when the transport didn't speak HTTP.
        var status: Int? {
            (response as? HTTPURLResponse)?.statusCode
        }
    }

    enum Responses {
        /// Statuses the spec declares below 400 for the operation.
        static func successStatuses(_ operation: Operation) -> Set<Int> {
            switch operation {
            case .getMuseumHours, .listSpecialEvents, .getSpecialEvent, .updateSpecialEvent, .getTicketCode:
                [200]
            case .createSpecialEvent, .buyMuseumTickets:
                [201]
            case .deleteSpecialEvent:
                [204]
            }
        }

        /// Gates a transport result through the spec: payload on an expected
        /// status, `ResponseError` otherwise. Operations with no declared
        /// success status fall back to the 2xx range.
        static func evaluate(
            _ operation: Operation,
            _ output: (data: Data, response: URLResponse)
        ) throws -> Data {
            guard let http = output.response as? HTTPURLResponse else {
                throw ResponseError(operation: operation, data: output.data, response: output.response)
            }
            let declared = successStatuses(operation)
            let status = http.statusCode
            let expected = declared.isEmpty ? (200 ..< 300).contains(status) : declared.contains(status)
            guard expected else {
                throw ResponseError(operation: operation, data: output.data, response: http)
            }
            return output.data
        }
    }

    // MARK: - Security (securitySchemes)

    enum Security {
        /// Scheme names the spec requires for an operation
        /// (OR-alternatives flattened into one set).
        static func schemes(_ operation: Operation) -> Set<String> {
            ["MuseumPlaceholderAuth"]
        }

        /// Whether the spec requires `MuseumPlaceholderAuth` for the operation.
        static func needsMuseumPlaceholderAuth(_ operation: Operation) -> Bool {
            schemes(operation).contains("MuseumPlaceholderAuth")
        }

        static func museumPlaceholderAuth(username: String, password: String) -> some RequestBuildable {
            Authorization.basic(username: username, password: password)
        }
    }

    // MARK: - Authorized

    struct MissingMuseumPlaceholderAuth: Error {}

    /// Operation + spec-required credentials as one block; apply the
    /// environment last: `.base(url).request()`.
    static func authorized(
        _ operation: Operation,
        museumPlaceholderAuth: (username: String, password: String)?
    ) -> some RequestBuildable {
        RequestBlock {
            operation
            if Security.needsMuseumPlaceholderAuth(operation) {
                if let museumPlaceholderAuth {
                    Security.museumPlaceholderAuth(username: museumPlaceholderAuth.username, password: museumPlaceholderAuth.password)
                } else {
                    RequestFailure(MissingMuseumPlaceholderAuth())
                }
            }
        }
    }

    // MARK: - Client

    /// The backend as one set of typed closures — swap any field to stub.
    struct Client {
        var getMuseumHours: (_ startDate: String?, _ page: Int?, _ limit: Int?) async throws -> MuseumHours
        var listSpecialEvents: (_ startDate: String?, _ endDate: String?, _ page: Int?, _ limit: Int?) async throws -> SpecialEventCollection
        var createSpecialEvent: (_ body: SpecialEvent) async throws -> SpecialEvent
        var getSpecialEvent: (_ eventId: String) async throws -> SpecialEvent
        var updateSpecialEvent: (_ eventId: String, _ body: SpecialEventFields) async throws -> SpecialEvent
        var deleteSpecialEvent: (_ eventId: String) async throws -> Void
        var buyMuseumTickets: (_ body: BuyMuseumTickets) async throws -> MuseumTicketsConfirmation
        var getTicketCode: (_ ticketId: String) async throws -> Data

        /// Wires the pipeline per operation: request → transport → evaluate
        /// → decode. Real or mock is decided entirely by the closures passed —
        /// this function has no opinion and no defaults. The mechanics live
        /// once in the pack-generic helpers; the table below is pure facts.
        static func wired(
            request: @escaping (Operation) throws -> URLRequest,
            transport: @escaping (URLRequest) async throws -> (Data, URLResponse),
            decoder: @escaping (Operation) -> JSONDecoder
        ) -> Client {
            func raw<each Input>(
                _ makeCase: @escaping (repeat each Input) -> Operation
            ) -> (repeat each Input) async throws -> Data {
                { (input: repeat each Input) in
                    let operation = makeCase(repeat each input)
                    return try Responses.evaluate(operation, try await transport(request(operation)))
                }
            }
            func endpoint<each Input, Output: Decodable>(
                _ makeCase: @escaping (repeat each Input) -> Operation,
                _ output: Output.Type
            ) -> (repeat each Input) async throws -> Output {
                { (input: repeat each Input) in
                    let operation = makeCase(repeat each input)
                    let data = try Responses.evaluate(operation, try await transport(request(operation)))
                    return try decoder(operation).decode(Output.self, from: data)
                }
            }
            func fire<each Input>(
                _ makeCase: @escaping (repeat each Input) -> Operation
            ) -> (repeat each Input) async throws -> Void {
                { (input: repeat each Input) in
                    let operation = makeCase(repeat each input)
                    _ = try Responses.evaluate(operation, try await transport(request(operation)))
                }
            }
            return Client(
                getMuseumHours: endpoint(Operation.getMuseumHours, MuseumHours.self),
                listSpecialEvents: endpoint(Operation.listSpecialEvents, SpecialEventCollection.self),
                createSpecialEvent: endpoint(Operation.createSpecialEvent, SpecialEvent.self),
                getSpecialEvent: endpoint(Operation.getSpecialEvent, SpecialEvent.self),
                updateSpecialEvent: endpoint(Operation.updateSpecialEvent, SpecialEvent.self),
                deleteSpecialEvent: fire(Operation.deleteSpecialEvent),
                buyMuseumTickets: endpoint(Operation.buyMuseumTickets, MuseumTicketsConfirmation.self),
                getTicketCode: raw(Operation.getTicketCode)
            )
        }
    }

    static let defaultBaseURL = URL(string: "https://redocly.com/_mock/docs/openapi/museum-api")
}
