// Generated by swift-spec. Do not edit.

import DeclarativeRequests
import Foundation

// MARK: - Model stubs
typealias APIDate = String
struct APIError: Codable {}
struct BuyMuseumTickets: Codable {}
typealias Email = String
typealias EventDates = [APIDate]
typealias EventDescription = String
typealias EventId = String
typealias EventLocation = String
typealias EventName = String
typealias EventPrice = Double
struct MuseumDailyHours: Codable {}
typealias MuseumHours = [MuseumDailyHours]
struct MuseumTicketsConfirmation: Codable {}
struct SpecialEvent: Codable {}
typealias SpecialEventCollection = [SpecialEvent]
struct SpecialEventFields: Codable {}
struct Ticket: Codable {}
typealias TicketCodeImage = Data
typealias TicketConfirmation = String
typealias TicketId = String
typealias TicketMessage = String
typealias TicketType = String

// MARK: - Endpoints
enum RedoclyMuseumAPIEndpoint: RequestBuildable {
    case getMuseumHours(startDate: String?, page: Int?, limit: Int?)
    case listSpecialEvents(startDate: String?, endDate: String?, page: Int?, limit: Int?)
    case createSpecialEvent(body: SpecialEvent)
    case getSpecialEvent(eventId: String)
    case updateSpecialEvent(eventId: String, body: SpecialEventFields)
    case deleteSpecialEvent(eventId: String)
    case buyMuseumTickets(body: BuyMuseumTickets)
    case getTicketCode(ticketId: String)

    static let defaultBaseURL = URL(string: "https://redocly.com/_mock/docs/openapi/museum-api")

    /// Security scheme names the spec requires for this endpoint
    /// (OR-alternatives flattened into one set).
    var securitySchemes: Set<String> {
        ["MuseumPlaceholderAuth"]
    }

    /// Whether the spec declares a security requirement for this endpoint.
    var needsAuth: Bool {
        !securitySchemes.isEmpty
    }

    @RequestBuilder var body: some RequestBuildable {
        switch self {
        case let .getMuseumHours(startDate, page, limit):
            Method.GET
            Endpoint("museum-hours")
            if let startDate {
                Query("startDate", startDate)
            }
            if let page {
                Query("page", String(page))
            }
            if let limit {
                Query("limit", String(limit))
            }
        case let .listSpecialEvents(startDate, endDate, page, limit):
            Method.GET
            Endpoint("special-events")
            if let startDate {
                Query("startDate", startDate)
            }
            if let endDate {
                Query("endDate", endDate)
            }
            if let page {
                Query("page", String(page))
            }
            if let limit {
                Query("limit", String(limit))
            }
        case let .createSpecialEvent(body):
            Method.POST
            Endpoint("special-events")
            RequestBody.json(body)
        case let .getSpecialEvent(eventId):
            Method.GET
            Endpoint("special-events/\(eventId)")
        case let .updateSpecialEvent(eventId, body):
            Method.PATCH
            Endpoint("special-events/\(eventId)")
            RequestBody.json(body)
        case let .deleteSpecialEvent(eventId):
            Method.DELETE
            Endpoint("special-events/\(eventId)")
        case let .buyMuseumTickets(body):
            Method.POST
            Endpoint("tickets")
            RequestBody.json(body)
        case let .getTicketCode(ticketId):
            Method.GET
            Endpoint("tickets/\(ticketId)/qr")
        }
    }
}
