// Generated by declarative-openapi. Do not edit.

import DeclarativeOpenAPIRuntime
import DeclarativeRequests
import Foundation

// The whole backend in one closed type — sections mirror the OpenAPI document.
public enum RedoclyMuseumAPI {
    // MARK: - Schemas (components.schemas)

    public typealias APIDate = String

    public struct APIError: Codable, Sendable {
        public var title: String? = nil
        public var type: String? = nil

        public init(
            title: String? = nil,
            type: String? = nil
        ) {
            self.title = title
            self.type = type
        }
    }

    public struct BuyMuseumTickets: Codable, Sendable {
        public var email: Email? = nil
        public var eventId: EventId? = nil
        public var ticketDate: APIDate
        public var ticketId: TicketId? = nil
        public var ticketType: TicketType

        public init(
            email: Email? = nil,
            eventId: EventId? = nil,
            ticketDate: APIDate,
            ticketId: TicketId? = nil,
            ticketType: TicketType
        ) {
            self.email = email
            self.eventId = eventId
            self.ticketDate = ticketDate
            self.ticketId = ticketId
            self.ticketType = ticketType
        }
    }

    public typealias Email = String

    public typealias EventDates = [APIDate]

    public typealias EventDescription = String

    public typealias EventId = String

    public typealias EventLocation = String

    public typealias EventName = String

    public typealias EventPrice = Double

    public struct MuseumDailyHours: Codable, Sendable {
        public var date: APIDate
        public var timeClose: String
        public var timeOpen: String

        public init(
            date: APIDate,
            timeClose: String,
            timeOpen: String
        ) {
            self.date = date
            self.timeClose = timeClose
            self.timeOpen = timeOpen
        }
    }

    public typealias MuseumHours = [MuseumDailyHours]

    public struct MuseumTicketsConfirmation: Codable, Sendable {
        public var confirmationCode: TicketConfirmation
        public var eventId: EventId? = nil
        public var message: TicketMessage
        public var ticketDate: APIDate
        public var ticketId: TicketId? = nil
        public var ticketType: TicketType

        public init(
            confirmationCode: TicketConfirmation,
            eventId: EventId? = nil,
            message: TicketMessage,
            ticketDate: APIDate,
            ticketId: TicketId? = nil,
            ticketType: TicketType
        ) {
            self.confirmationCode = confirmationCode
            self.eventId = eventId
            self.message = message
            self.ticketDate = ticketDate
            self.ticketId = ticketId
            self.ticketType = ticketType
        }
    }

    public struct SpecialEvent: Codable, Sendable {
        public var dates: EventDates
        public var eventDescription: EventDescription
        public var eventId: EventId? = nil
        public var location: EventLocation
        public var name: EventName
        public var price: EventPrice

        public init(
            dates: EventDates,
            eventDescription: EventDescription,
            eventId: EventId? = nil,
            location: EventLocation,
            name: EventName,
            price: EventPrice
        ) {
            self.dates = dates
            self.eventDescription = eventDescription
            self.eventId = eventId
            self.location = location
            self.name = name
            self.price = price
        }
    }

    public typealias SpecialEventCollection = [SpecialEvent]

    public struct SpecialEventFields: Codable, Sendable {
        public var dates: EventDates? = nil
        public var eventDescription: EventDescription? = nil
        public var location: EventLocation? = nil
        public var name: EventName? = nil
        public var price: EventPrice? = nil

        public init(
            dates: EventDates? = nil,
            eventDescription: EventDescription? = nil,
            location: EventLocation? = nil,
            name: EventName? = nil,
            price: EventPrice? = nil
        ) {
            self.dates = dates
            self.eventDescription = eventDescription
            self.location = location
            self.name = name
            self.price = price
        }
    }

    public struct Ticket: Codable, Sendable {
        public var eventId: EventId? = nil
        public var ticketDate: APIDate
        public var ticketId: TicketId? = nil
        public var ticketType: TicketType

        public init(
            eventId: EventId? = nil,
            ticketDate: APIDate,
            ticketId: TicketId? = nil,
            ticketType: TicketType
        ) {
            self.eventId = eventId
            self.ticketDate = ticketDate
            self.ticketId = ticketId
            self.ticketType = ticketType
        }
    }

    public typealias TicketCodeImage = Data

    public typealias TicketConfirmation = String

    public typealias TicketId = String

    public typealias TicketMessage = String

    public enum TicketType: String, Codable, Sendable {
        case event
        case general
    }

    // MARK: - Operations (paths)

    // each operation IS a block
    public enum Operation: RequestBuildable {
        case getMuseumHours(startDate: String?, page: Int?, limit: Int?)
        case listSpecialEvents(startDate: String?, endDate: String?, page: Int?, limit: Int?)
        case createSpecialEvent(body: SpecialEvent)
        case getSpecialEvent(eventId: String)
        case updateSpecialEvent(eventId: String, body: SpecialEventFields)
        case deleteSpecialEvent(eventId: String)
        case buyMuseumTickets(body: BuyMuseumTickets)
        case getTicketCode(ticketId: String)

        public var body: some RequestBuildable {
            switch self {
            case let .getMuseumHours(startDate, page, limit):
                Method.GET
                Endpoint("museum-hours")
                if let startDate {
                    Query("startDate", startDate)
                }
                if let page {
                    Query("page", String(page))
                }
                if let limit {
                    Query("limit", String(limit))
                }
            case let .listSpecialEvents(startDate, endDate, page, limit):
                Method.GET
                Endpoint("special-events")
                if let startDate {
                    Query("startDate", startDate)
                }
                if let endDate {
                    Query("endDate", endDate)
                }
                if let page {
                    Query("page", String(page))
                }
                if let limit {
                    Query("limit", String(limit))
                }
            case let .createSpecialEvent(body):
                Method.POST
                Endpoint("special-events")
                RequestBody.json(body)
            case let .getSpecialEvent(eventId):
                Method.GET
                Endpoint("special-events/\(eventId)")
            case let .updateSpecialEvent(eventId, body):
                Method.PATCH
                Endpoint("special-events/\(eventId)")
                RequestBody.json(body)
            case let .deleteSpecialEvent(eventId):
                Method.DELETE
                Endpoint("special-events/\(eventId)")
            case let .buyMuseumTickets(body):
                Method.POST
                Endpoint("tickets")
                RequestBody.json(body)
            case let .getTicketCode(ticketId):
                Method.GET
                Endpoint("tickets/\(ticketId)/qr")
            }
        }
    }

    // MARK: - Responses (responses)

    public enum Responses {
        /// Statuses the spec declares below 400 for the operation.
        public static func successStatuses(_ operation: Operation) -> Set<Int> {
            switch operation {
            case .getMuseumHours, .listSpecialEvents, .getSpecialEvent, .updateSpecialEvent, .getTicketCode:
                [200]
            case .createSpecialEvent, .buyMuseumTickets:
                [201]
            case .deleteSpecialEvent:
                [204]
            }
        }
    }

    // MARK: - Security (securitySchemes)

    public enum Security {
        /// Scheme names the spec requires for an operation
        /// (OR-alternatives flattened into one set).
        public static func schemes(_ operation: Operation) -> Set<String> {
            ["MuseumPlaceholderAuth"]
        }

        /// Whether the spec requires `MuseumPlaceholderAuth` for the operation.
        public static func needsMuseumPlaceholderAuth(_ operation: Operation) -> Bool {
            schemes(operation).contains("MuseumPlaceholderAuth")
        }

        public static func museumPlaceholderAuth(username: String, password: String) -> some RequestBuildable {
            Authorization.basic(username: username, password: password)
        }
    }

    // MARK: - Authorized

    public struct MissingMuseumPlaceholderAuth: Error {
        public init() {}
    }

    /// Operation + spec-required credentials as one block; apply the
    /// environment last: `.base(url).request()`.
    public static func authorized(
        _ operation: Operation,
        museumPlaceholderAuth: (username: String, password: String)?
    ) -> some RequestBuildable {
        RequestBlock {
            operation
            if Security.needsMuseumPlaceholderAuth(operation) {
                if let museumPlaceholderAuth {
                    Security.museumPlaceholderAuth(username: museumPlaceholderAuth.username, password: museumPlaceholderAuth.password)
                } else {
                    RequestFailure(MissingMuseumPlaceholderAuth())
                }
            }
        }
    }

    // MARK: - Client

    /// The backend as one set of typed closures — swap any field to stub.
    public struct Client: Sendable {
        public var getMuseumHours: @Sendable (_ startDate: String?, _ page: Int?, _ limit: Int?) async throws -> MuseumHours
        public var listSpecialEvents: @Sendable (_ startDate: String?, _ endDate: String?, _ page: Int?, _ limit: Int?) async throws -> SpecialEventCollection
        public var createSpecialEvent: @Sendable (_ body: SpecialEvent) async throws -> SpecialEvent
        public var getSpecialEvent: @Sendable (_ eventId: String) async throws -> SpecialEvent
        public var updateSpecialEvent: @Sendable (_ eventId: String, _ body: SpecialEventFields) async throws -> SpecialEvent
        public var deleteSpecialEvent: @Sendable (_ eventId: String) async throws -> Void
        public var buyMuseumTickets: @Sendable (_ body: BuyMuseumTickets) async throws -> MuseumTicketsConfirmation
        public var getTicketCode: @Sendable (_ ticketId: String) async throws -> Data

        /// A whole backend that implements nothing: every field traps by name.
        /// State the operations under test by assignment, leave the rest to
        /// announce themselves. Unreachable in production — `wired` fills every
        /// field — so a trap is always a hand-built client missing one.
        public static var unimplemented: Client {
            Client(
                getMuseumHours: ClosureUtilities.unimplemented("getMuseumHours"),
                listSpecialEvents: ClosureUtilities.unimplemented("listSpecialEvents"),
                createSpecialEvent: ClosureUtilities.unimplemented("createSpecialEvent"),
                getSpecialEvent: ClosureUtilities.unimplemented("getSpecialEvent"),
                updateSpecialEvent: ClosureUtilities.unimplemented("updateSpecialEvent"),
                deleteSpecialEvent: ClosureUtilities.unimplemented("deleteSpecialEvent"),
                buyMuseumTickets: ClosureUtilities.unimplemented("buyMuseumTickets"),
                getTicketCode: ClosureUtilities.unimplemented("getTicketCode")
            )
        }

        /// Wires the typed surface over the (Operation) → Data seam. Real,
        /// mocked, or middleware-wrapped is decided entirely by the closures
        /// passed — no opinion, no defaults. The mechanics live once in the
        /// runtime's ClientBuilder; the table below is pure facts.
        public static func wired(
            execute: @escaping @Sendable (Operation) async throws -> Data,
            decoder: @escaping @Sendable (Operation) -> JSONDecoder
        ) -> Client {
            let build = ClientBuilder(execute: execute, decoder: decoder)
            return Client(
                getMuseumHours: build.endpoint(Operation.getMuseumHours, MuseumHours.self),
                listSpecialEvents: build.endpoint(Operation.listSpecialEvents, SpecialEventCollection.self),
                createSpecialEvent: build.endpoint(Operation.createSpecialEvent, SpecialEvent.self),
                getSpecialEvent: build.endpoint(Operation.getSpecialEvent, SpecialEvent.self),
                updateSpecialEvent: build.endpoint(Operation.updateSpecialEvent, SpecialEvent.self),
                deleteSpecialEvent: build.fire(Operation.deleteSpecialEvent),
                buyMuseumTickets: build.endpoint(Operation.buyMuseumTickets, MuseumTicketsConfirmation.self),
                getTicketCode: build.raw(Operation.getTicketCode)
            )
        }
    }

    public static let defaultBaseURL = URL(string: "https://redocly.com/_mock/docs/openapi/museum-api")
}
