// Generated by swift-spec. Do not edit.
// Client-only: operations requiring AdminAuth are not generated.

import DeclarativeRequests
import Foundation

// MARK: - Model stubs
struct AccessTokenResponseSchema: Codable {}
struct CredentialCreationOptions: Codable {}
struct CredentialRequestOptions: Codable {}
struct CustomOAuthProviderSchema: Codable {}
struct ErrorSchema: Codable {}
struct GoTrueSecurity: Codable {}
struct IdentitySchema: Codable {}
struct MFAFactorSchema: Codable {}
struct OAuthClientSchema: Codable {}
struct PostFactorsBody: Codable {}
struct PostFactorsFactorIdChallengeBody: Codable {}
struct PostFactorsFactorIdVerifyBody: Codable {}
struct PostInviteBody: Codable {}
struct PostMagiclinkBody: Codable {}
struct PostOauthAuthorizationsAuthorizationIdConsentBody: Codable {}
struct PostOauthClientsRegisterBody: Codable {}
struct PostOtpBody: Codable {}
struct PostRecoverBody: Codable {}
struct PostResendBody: Codable {}
struct PostSignupBody: Codable {}
struct PostSsoBody: Codable {}
struct PostTokenBody: Codable {}
struct PostVerifyBody: Codable {}
struct PublicKeyCredentialDescriptor: Codable {}
struct PutUserBody: Codable {}
struct SAMLAttributeMappingSchema: Codable {}
struct SSOProviderSchema: Codable {}
struct TOTPPhoneChallengeResponse: Codable {}
struct UserSchema: Codable {}
struct WebAuthnChallengeResponse: Codable {}

// MARK: - Endpoints
enum SupabaseAuthRESTAPIEndpoint: RequestBuildable {
    case getAuthorize(provider: String, scopes: String, inviteToken: String?, redirectTo: String?, codeChallengeMethod: String?)
    case getCallback
    case postCallback
    case postFactors(body: PostFactorsBody)
    case deleteFactorsFactorId(factorId: String)
    case postFactorsFactorIdChallenge(factorId: String, body: PostFactorsFactorIdChallengeBody)
    case postFactorsFactorIdVerify(factorId: String, body: PostFactorsFactorIdVerifyBody)
    case getHealth
    case postInvite(body: PostInviteBody)
    case postLogout(scope: String?)
    case postMagiclink(body: PostMagiclinkBody)
    case getOauthAuthorizationsAuthorizationId(authorizationId: String)
    case postOauthAuthorizationsAuthorizationIdConsent(authorizationId: String, body: PostOauthAuthorizationsAuthorizationIdConsentBody)
    case getOauthAuthorize(responseType: String, clientId: String, redirectUri: String, scope: String?, state: String?, codeChallenge: String, codeChallengeMethod: String)
    case postOauthClientsRegister(body: PostOauthClientsRegisterBody)
    case postOauthToken
    case postOtp(body: PostOtpBody)
    case postReauthenticate
    case postRecover(body: PostRecoverBody)
    case postResend(body: PostResendBody)
    case postSamlAcs(relayState: String?, sAMLArt: String?, sAMLResponse: String?)
    case getSamlMetadata(download: Bool?)
    case getSettings
    case postSignup(body: PostSignupBody)
    case postSso(body: PostSsoBody)
    case postToken(grantType: String, body: PostTokenBody)
    case getUser
    case putUser(body: PutUserBody)
    case getUserIdentitiesAuthorize(provider: String, scopes: String, redirectTo: String?, codeChallengeMethod: String?)
    case deleteUserIdentitiesIdentityId(identityId: String)
    case getUserOauthGrants
    case deleteUserOauthGrants(clientId: String)
    case getVerify(token: String, type: String, redirectTo: String?)
    case postVerify(body: PostVerifyBody)

    /// Server URL is templated — supply a resolved base URL: `https://{project}.supabase.co/auth/v1`

    /// Security scheme names the spec requires for this endpoint
    /// (OR-alternatives flattened into one set).
    var securitySchemes: Set<String> {
        switch self {
        case .getAuthorize, .getCallback, .getHealth, .postInvite, .postMagiclink,
            .postOtp, .postRecover, .postResend, .getSamlMetadata, .getSettings,
            .postSignup, .postSso, .postToken, .getVerify, .postVerify:
            ["APIKeyAuth"]
        case .postCallback, .getOauthAuthorize, .postOauthClientsRegister, .postOauthToken, .postSamlAcs:
            []
        case .postFactors, .deleteFactorsFactorId, .postFactorsFactorIdChallenge, .postFactorsFactorIdVerify, .postLogout,
            .getOauthAuthorizationsAuthorizationId, .postOauthAuthorizationsAuthorizationIdConsent, .postReauthenticate, .getUser, .putUser,
            .getUserIdentitiesAuthorize, .deleteUserIdentitiesIdentityId, .getUserOauthGrants, .deleteUserOauthGrants:
            ["APIKeyAuth", "UserAuth"]
        }
    }

    /// Whether the spec requires the `APIKeyAuth` scheme for this endpoint.
    var needsAPIKeyAuth: Bool {
        securitySchemes.contains("APIKeyAuth")
    }

    /// Whether the spec requires the `UserAuth` scheme for this endpoint.
    var needsUserAuth: Bool {
        securitySchemes.contains("UserAuth")
    }

    @RequestBuilder var body: some RequestBuildable {
        switch self {
        case let .getAuthorize(provider, scopes, inviteToken, redirectTo, codeChallengeMethod):
            Method.GET
            Endpoint("authorize")
            Query("provider", provider)
            Query("scopes", scopes)
            if let inviteToken {
                Query("invite_token", inviteToken)
            }
            if let redirectTo {
                Query("redirect_to", redirectTo)
            }
            if let codeChallengeMethod {
                Query("code_challenge_method", codeChallengeMethod)
            }
        case .getCallback:
            Method.GET
            Endpoint("callback")
        case .postCallback:
            Method.POST
            Endpoint("callback")
        case let .postFactors(body):
            Method.POST
            Endpoint("factors")
            RequestBody.json(body)
        case let .deleteFactorsFactorId(factorId):
            Method.DELETE
            Endpoint("factors/\(factorId)")
        case let .postFactorsFactorIdChallenge(factorId, body):
            Method.POST
            Endpoint("factors/\(factorId)/challenge")
            RequestBody.json(body)
        case let .postFactorsFactorIdVerify(factorId, body):
            Method.POST
            Endpoint("factors/\(factorId)/verify")
            RequestBody.json(body)
        case .getHealth:
            Method.GET
            Endpoint("health")
        case let .postInvite(body):
            Method.POST
            Endpoint("invite")
            RequestBody.json(body)
        case let .postLogout(scope):
            Method.POST
            Endpoint("logout")
            if let scope {
                Query("scope", scope)
            }
        case let .postMagiclink(body):
            Method.POST
            Endpoint("magiclink")
            RequestBody.json(body)
        case let .getOauthAuthorizationsAuthorizationId(authorizationId):
            Method.GET
            Endpoint("oauth/authorizations/\(authorizationId)")
        case let .postOauthAuthorizationsAuthorizationIdConsent(authorizationId, body):
            Method.POST
            Endpoint("oauth/authorizations/\(authorizationId)/consent")
            RequestBody.json(body)
        case let .getOauthAuthorize(responseType, clientId, redirectUri, scope, state, codeChallenge, codeChallengeMethod):
            Method.GET
            Endpoint("oauth/authorize")
            Query("response_type", responseType)
            Query("client_id", clientId)
            Query("redirect_uri", redirectUri)
            if let scope {
                Query("scope", scope)
            }
            if let state {
                Query("state", state)
            }
            Query("code_challenge", codeChallenge)
            Query("code_challenge_method", codeChallengeMethod)
        case let .postOauthClientsRegister(body):
            Method.POST
            Endpoint("oauth/clients/register")
            RequestBody.json(body)
        case .postOauthToken:
            Method.POST
            Endpoint("oauth/token")
        case let .postOtp(body):
            Method.POST
            Endpoint("otp")
            RequestBody.json(body)
        case .postReauthenticate:
            Method.POST
            Endpoint("reauthenticate")
        case let .postRecover(body):
            Method.POST
            Endpoint("recover")
            RequestBody.json(body)
        case let .postResend(body):
            Method.POST
            Endpoint("resend")
            RequestBody.json(body)
        case let .postSamlAcs(relayState, sAMLArt, sAMLResponse):
            Method.POST
            Endpoint("saml/acs")
            if let relayState {
                Query("RelayState", relayState)
            }
            if let sAMLArt {
                Query("SAMLArt", sAMLArt)
            }
            if let sAMLResponse {
                Query("SAMLResponse", sAMLResponse)
            }
        case let .getSamlMetadata(download):
            Method.GET
            Endpoint("saml/metadata")
            if let download {
                Query("download", String(download))
            }
        case .getSettings:
            Method.GET
            Endpoint("settings")
        case let .postSignup(body):
            Method.POST
            Endpoint("signup")
            RequestBody.json(body)
        case let .postSso(body):
            Method.POST
            Endpoint("sso")
            RequestBody.json(body)
        case let .postToken(grantType, body):
            Method.POST
            Endpoint("token")
            Query("grant_type", grantType)
            RequestBody.json(body)
        case .getUser:
            Method.GET
            Endpoint("user")
        case let .putUser(body):
            Method.PUT
            Endpoint("user")
            RequestBody.json(body)
        case let .getUserIdentitiesAuthorize(provider, scopes, redirectTo, codeChallengeMethod):
            Method.GET
            Endpoint("user/identities/authorize")
            Query("provider", provider)
            Query("scopes", scopes)
            if let redirectTo {
                Query("redirect_to", redirectTo)
            }
            if let codeChallengeMethod {
                Query("code_challenge_method", codeChallengeMethod)
            }
        case let .deleteUserIdentitiesIdentityId(identityId):
            Method.DELETE
            Endpoint("user/identities/\(identityId)")
        case .getUserOauthGrants:
            Method.GET
            Endpoint("user/oauth/grants")
        case let .deleteUserOauthGrants(clientId):
            Method.DELETE
            Endpoint("user/oauth/grants")
            Query("client_id", clientId)
        case let .getVerify(token, type, redirectTo):
            Method.GET
            Endpoint("verify")
            Query("token", token)
            Query("type", type)
            if let redirectTo {
                Query("redirect_to", redirectTo)
            }
        case let .postVerify(body):
            Method.POST
            Endpoint("verify")
            RequestBody.json(body)
        }
    }
}
