// Generated by declarative-openapi. Do not edit.

import DeclarativeOpenAPIRuntime
import DeclarativeRequests
import Foundation

// The whole backend in one closed type — sections mirror the OpenAPI document.
public enum SwaggerPetstore {
    // MARK: - Schemas (components.schemas)

    public struct APIError: Codable, Sendable {
        public var code: Int
        public var message: String

        public init(
            code: Int,
            message: String
        ) {
            self.code = code
            self.message = message
        }
    }

    public struct Pet: Codable, Sendable {
        public var id: Int
        public var name: String
        public var tag: String? = nil

        public init(
            id: Int,
            name: String,
            tag: String? = nil
        ) {
            self.id = id
            self.name = name
            self.tag = tag
        }
    }

    public typealias Pets = [Pet]

    // MARK: - Operations (paths)

    // each operation IS a block
    public enum Operation: RequestBuildable {
        case listPets(limit: Int?)
        case createPets(body: Pet)
        case showPetById(petId: String)

        public var body: some RequestBuildable {
            switch self {
            case let .listPets(limit):
                Method.GET
                Endpoint("pets")
                if let limit {
                    Query("limit", String(limit))
                }
            case let .createPets(body):
                Method.POST
                Endpoint("pets")
                RequestBody.json(body)
            case let .showPetById(petId):
                Method.GET
                Endpoint("pets/\(petId)")
            }
        }
    }

    // MARK: - Responses (responses)

    public enum Responses {
        /// Statuses the spec declares below 400 for the operation.
        public static func successStatuses(_ operation: Operation) -> Set<Int> {
            switch operation {
            case .listPets, .showPetById:
                [200]
            case .createPets:
                [201]
            }
        }
    }

    // MARK: - Client

    /// The backend as one set of typed closures — swap any field to stub.
    public struct Client: Sendable {
        public var listPets: @Sendable (_ limit: Int?) async throws -> Pets
        public var createPets: @Sendable (_ body: Pet) async throws -> Void
        public var showPetById: @Sendable (_ petId: String) async throws -> Pet

        /// A whole backend that implements nothing: every field traps by name.
        /// State the operations under test by assignment, leave the rest to
        /// announce themselves. Unreachable in production — `wired` fills every
        /// field — so a trap is always a hand-built client missing one.
        public static var unimplemented: Client {
            Client(
                listPets: ClosureUtilities.unimplemented("listPets"),
                createPets: ClosureUtilities.unimplemented("createPets"),
                showPetById: ClosureUtilities.unimplemented("showPetById")
            )
        }

        /// Wires the typed surface over the (Operation) → Data seam. Real,
        /// mocked, or middleware-wrapped is decided entirely by the closures
        /// passed — no opinion, no defaults. The mechanics live once in the
        /// runtime's ClientBuilder; the table below is pure facts.
        public static func wired(
            execute: @escaping @Sendable (Operation) async throws -> Data,
            decoder: @escaping @Sendable (Operation) -> JSONDecoder
        ) -> Client {
            let build = ClientBuilder(execute: execute, decoder: decoder)
            return Client(
                listPets: build.endpoint(Operation.listPets, Pets.self),
                createPets: build.fire(Operation.createPets),
                showPetById: build.endpoint(Operation.showPetById, Pet.self)
            )
        }
    }

    public static let defaultBaseURL = URL(string: "http://petstore.swagger.io/v1")
}
