// Generated by declarative-openapi. Do not edit.

import DeclarativeRequests
import Foundation

// The whole backend in one closed type — sections mirror the OpenAPI document.
enum SwaggerPetstore {
    // MARK: - Schemas (components.schemas)

    struct APIError: Codable {
        var code: Int
        var message: String
    }

    struct Pet: Codable {
        var id: Int
        var name: String
        var tag: String? = nil
    }

    typealias Pets = [Pet]

    // MARK: - Operations (paths)

    // each operation IS a block
    enum Operation: RequestBuildable {
        case listPets(limit: Int?)
        case createPets(body: Pet)
        case showPetById(petId: String)

        var body: some RequestBuildable {
            switch self {
            case let .listPets(limit):
                Method.GET
                Endpoint("pets")
                if let limit {
                    Query("limit", String(limit))
                }
            case let .createPets(body):
                Method.POST
                Endpoint("pets")
                RequestBody.json(body)
            case let .showPetById(petId):
                Method.GET
                Endpoint("pets/\(petId)")
            }
        }
    }

    // MARK: - Responses (responses)

    /// One error, nothing lost: status, payload, and the raw response —
    /// decode the spec's error model from `data` in the layer that needs it.
    struct ResponseError: Error {
        let operation: Operation
        let data: Data
        let response: HTTPURLResponse
    }

    /// Thrown when the transport yields something other than HTTP —
    /// same rule, nothing lost.
    struct NonHTTPResponse: Error {
        let operation: Operation
        let data: Data
        let response: URLResponse
    }

    enum Responses {
        /// Statuses the spec declares below 400 for the operation.
        static func successStatuses(_ operation: Operation) -> Set<Int> {
            switch operation {
            case .listPets, .showPetById:
                [200]
            case .createPets:
                [201]
            }
        }

        /// Gates a transport result through the spec: payload on an expected
        /// status, `ResponseError` otherwise. Operations with no declared
        /// success status fall back to the 2xx range.
        static func evaluate(
            _ operation: Operation,
            _ output: (data: Data, response: URLResponse)
        ) throws -> Data {
            guard let http = output.response as? HTTPURLResponse else {
                throw NonHTTPResponse(operation: operation, data: output.data, response: output.response)
            }
            let declared = successStatuses(operation)
            let status = http.statusCode
            let expected = declared.isEmpty ? (200 ..< 300).contains(status) : declared.contains(status)
            guard expected else {
                throw ResponseError(operation: operation, data: output.data, response: http)
            }
            return output.data
        }
    }

    static let defaultBaseURL = URL(string: "http://petstore.swagger.io/v1")
}
