// Generated by declarative-openapi. Do not edit.

import DeclarativeOpenAPIRuntime
import DeclarativeRequests
import Foundation

// The whole backend in one closed type — sections mirror the OpenAPI document.
public enum BinanceSpotAPI {
    // MARK: - Schemas (components.schemas)

    public struct AggTrade: Codable, Sendable {
        public var M: Bool
        public var t: Bool
        public var a: Int
        public var f: Int
        public var l: Int
        public var m: Bool
        public var p: String
        public var q: String

        public init(
            M: Bool,
            t: Bool,
            a: Int,
            f: Int,
            l: Int,
            m: Bool,
            p: String,
            q: String
        ) {
            self.M = M
            self.t = t
            self.a = a
            self.f = f
            self.l = l
            self.m = m
            self.p = p
            self.q = q
        }

        enum CodingKeys: String, CodingKey {
            case M
            case t = "T"
            case a
            case f
            case l
            case m
            case p
            case q
        }
    }

    public struct BookTicker: Codable, Sendable {
        public var askPrice: String
        public var askQty: String
        public var bidPrice: String
        public var bidQty: String
        public var symbol: String

        public init(
            askPrice: String,
            askQty: String,
            bidPrice: String,
            bidQty: String,
            symbol: String
        ) {
            self.askPrice = askPrice
            self.askQty = askQty
            self.bidPrice = bidPrice
            self.bidQty = bidQty
            self.symbol = symbol
        }
    }

    public typealias BookTickerList = [BookTicker]

    public struct DayTicker: Codable, Sendable {
        public var closeTime: Int
        public var count: Int
        public var firstId: Int
        public var highPrice: String
        public var lastId: Int
        public var lastPrice: String
        public var lowPrice: String
        public var openPrice: String
        public var openTime: Int
        public var priceChange: String
        public var priceChangePercent: String
        public var quoteVolume: String
        public var symbol: String
        public var volume: String
        public var weightedAvgPrice: String

        public init(
            closeTime: Int,
            count: Int,
            firstId: Int,
            highPrice: String,
            lastId: Int,
            lastPrice: String,
            lowPrice: String,
            openPrice: String,
            openTime: Int,
            priceChange: String,
            priceChangePercent: String,
            quoteVolume: String,
            symbol: String,
            volume: String,
            weightedAvgPrice: String
        ) {
            self.closeTime = closeTime
            self.count = count
            self.firstId = firstId
            self.highPrice = highPrice
            self.lastId = lastId
            self.lastPrice = lastPrice
            self.lowPrice = lowPrice
            self.openPrice = openPrice
            self.openTime = openTime
            self.priceChange = priceChange
            self.priceChangePercent = priceChangePercent
            self.quoteVolume = quoteVolume
            self.symbol = symbol
            self.volume = volume
            self.weightedAvgPrice = weightedAvgPrice
        }
    }

    public typealias DayTickerList = [DayTicker]

    public struct GetApiV3AvgPriceResponse: Codable, Sendable {
        public var closeTime: Int
        public var mins: Int
        public var price: String

        public init(
            closeTime: Int,
            mins: Int,
            price: String
        ) {
            self.closeTime = closeTime
            self.mins = mins
            self.price = price
        }
    }

    public struct GetApiV3DepthResponse: Codable, Sendable {
        public var asks: [[String]]
        public var bids: [[String]]
        public var lastUpdateId: Int

        public init(
            asks: [[String]],
            bids: [[String]],
            lastUpdateId: Int
        ) {
            self.asks = asks
            self.bids = bids
            self.lastUpdateId = lastUpdateId
        }
    }

    public struct GetApiV3ExchangeInfoResponse: Codable, Sendable {
        public var exchangeFilters: [String]
        public var rateLimits: [String]
        public var serverTime: Int
        public var symbols: [String]
        public var timezone: String

        public init(
            exchangeFilters: [String],
            rateLimits: [String],
            serverTime: Int,
            symbols: [String],
            timezone: String
        ) {
            self.exchangeFilters = exchangeFilters
            self.rateLimits = rateLimits
            self.serverTime = serverTime
            self.symbols = symbols
            self.timezone = timezone
        }
    }

    public struct GetApiV3PingResponse: Codable, Sendable {
        public init() {}
    }

    public struct GetApiV3TickerResponse: Codable, Sendable {
        public var closeTime: Int
        public var count: Int
        public var firstId: Int
        public var highPrice: String
        public var lastId: Int
        public var lastPrice: String
        public var lowPrice: String
        public var openPrice: String
        public var openTime: Int
        public var priceChange: String
        public var priceChangePercent: String
        public var quoteVolume: String
        public var symbol: String
        public var volume: String
        public var weightedAvgPrice: String

        public init(
            closeTime: Int,
            count: Int,
            firstId: Int,
            highPrice: String,
            lastId: Int,
            lastPrice: String,
            lowPrice: String,
            openPrice: String,
            openTime: Int,
            priceChange: String,
            priceChangePercent: String,
            quoteVolume: String,
            symbol: String,
            volume: String,
            weightedAvgPrice: String
        ) {
            self.closeTime = closeTime
            self.count = count
            self.firstId = firstId
            self.highPrice = highPrice
            self.lastId = lastId
            self.lastPrice = lastPrice
            self.lowPrice = lowPrice
            self.openPrice = openPrice
            self.openTime = openTime
            self.priceChange = priceChange
            self.priceChangePercent = priceChangePercent
            self.quoteVolume = quoteVolume
            self.symbol = symbol
            self.volume = volume
            self.weightedAvgPrice = weightedAvgPrice
        }
    }

    public struct GetApiV3TimeResponse: Codable, Sendable {
        public var serverTime: Int

        public init(
            serverTime: Int
        ) {
            self.serverTime = serverTime
        }
    }

    public struct GetSapiV1AccountApiRestrictionsResponse: Codable, Sendable {
        public var createTime: Int
        public var enableFutures: Bool
        public var enableInternalTransfer: Bool
        public var enableMargin: Bool
        public var enablePortfolioMarginTrading: Bool? = nil
        public var enableReading: Bool
        public var enableSpotAndMarginTrading: Bool
        public var enableVanillaOptions: Bool
        public var enableWithdrawals: Bool
        public var ipRestrict: Bool
        public var permitsUniversalTransfer: Bool
        public var tradingAuthorityExpirationTime: Int

        public init(
            createTime: Int,
            enableFutures: Bool,
            enableInternalTransfer: Bool,
            enableMargin: Bool,
            enablePortfolioMarginTrading: Bool? = nil,
            enableReading: Bool,
            enableSpotAndMarginTrading: Bool,
            enableVanillaOptions: Bool,
            enableWithdrawals: Bool,
            ipRestrict: Bool,
            permitsUniversalTransfer: Bool,
            tradingAuthorityExpirationTime: Int
        ) {
            self.createTime = createTime
            self.enableFutures = enableFutures
            self.enableInternalTransfer = enableInternalTransfer
            self.enableMargin = enableMargin
            self.enablePortfolioMarginTrading = enablePortfolioMarginTrading
            self.enableReading = enableReading
            self.enableSpotAndMarginTrading = enableSpotAndMarginTrading
            self.enableVanillaOptions = enableVanillaOptions
            self.enableWithdrawals = enableWithdrawals
            self.ipRestrict = ipRestrict
            self.permitsUniversalTransfer = permitsUniversalTransfer
            self.tradingAuthorityExpirationTime = tradingAuthorityExpirationTime
        }
    }

    public struct GetSapiV1AccountApiTradingStatusResponse: Codable, Sendable {
        public var data: String

        public init(
            data: String
        ) {
            self.data = data
        }
    }

    public struct GetSapiV1AccountInfoResponse: Codable, Sendable {
        public var isFutureEnabled: Bool
        public var isMarginEnabled: Bool
        public var vipLevel: Int

        public init(
            isFutureEnabled: Bool,
            isMarginEnabled: Bool,
            vipLevel: Int
        ) {
            self.isFutureEnabled = isFutureEnabled
            self.isMarginEnabled = isMarginEnabled
            self.vipLevel = vipLevel
        }
    }

    public struct GetSapiV1AccountStatusResponse: Codable, Sendable {
        public var data: String

        public init(
            data: String
        ) {
            self.data = data
        }
    }

    public struct GetSapiV1AssetAssetDetailResponse: Codable, Sendable {
        public var cTR: String

        public init(
            cTR: String
        ) {
            self.cTR = cTR
        }

        enum CodingKeys: String, CodingKey {
            case cTR = "CTR"
        }
    }

    public struct GetSapiV1AssetAssetDividendResponse: Codable, Sendable {
        public var rows: [String]
        public var total: Int

        public init(
            rows: [String],
            total: Int
        ) {
            self.rows = rows
            self.total = total
        }
    }

    public struct GetSapiV1AssetConvertTransferQueryByPageResponse: Codable, Sendable {
        public var rows: [String]
        public var total: Int

        public init(
            rows: [String],
            total: Int
        ) {
            self.rows = rows
            self.total = total
        }
    }

    public struct GetSapiV1AssetCustodyTransferHistoryResponse: Codable, Sendable {
        public var rows: [String]
        public var total: Int

        public init(
            rows: [String],
            total: Int
        ) {
            self.rows = rows
            self.total = total
        }
    }

    public struct GetSapiV1AssetDribbletResponse: Codable, Sendable {
        public var total: Int
        public var userAssetDribblets: [String]

        public init(
            total: Int,
            userAssetDribblets: [String]
        ) {
            self.total = total
            self.userAssetDribblets = userAssetDribblets
        }
    }

    public struct GetSapiV1AssetLedgerTransferCloudMiningQueryByPageResponse: Codable, Sendable {
        public var rows: [String]
        public var total: Int

        public init(
            rows: [String],
            total: Int
        ) {
            self.rows = rows
            self.total = total
        }
    }

    public struct GetSapiV1AssetTransferResponse: Codable, Sendable {
        public var rows: [String]
        public var total: Int

        public init(
            rows: [String],
            total: Int
        ) {
            self.rows = rows
            self.total = total
        }
    }

    public struct GetSapiV1CapitalContractConvertibleCoinsResponse: Codable, Sendable {
        public var coins: [String]
        public var convertEnabled: Bool
        public var exchangeRates: String

        public init(
            coins: [String],
            convertEnabled: Bool,
            exchangeRates: String
        ) {
            self.coins = coins
            self.convertEnabled = convertEnabled
            self.exchangeRates = exchangeRates
        }
    }

    public struct GetSapiV1CapitalDepositAddressResponse: Codable, Sendable {
        public var address: String
        public var coin: String
        public var tag: String
        public var url: String

        public init(
            address: String,
            coin: String,
            tag: String,
            url: String
        ) {
            self.address = address
            self.coin = coin
            self.tag = tag
            self.url = url
        }
    }

    public struct GetSapiV1SystemStatusResponse: Codable, Sendable {
        public var msg: String
        public var status: Int

        public init(
            msg: String,
            status: Int
        ) {
            self.msg = msg
            self.status = status
        }
    }

    public struct PostSapiV1AccountDisableFastWithdrawSwitchResponse: Codable, Sendable {
        public init() {}
    }

    public struct PostSapiV1AccountEnableFastWithdrawSwitchResponse: Codable, Sendable {
        public init() {}
    }

    public struct PostSapiV1AssetConvertTransferResponse: Codable, Sendable {
        public var status: String
        public var tranId: Int

        public init(
            status: String,
            tranId: Int
        ) {
            self.status = status
            self.tranId = tranId
        }
    }

    public struct PostSapiV1AssetDustBtcResponse: Codable, Sendable {
        public var details: [String]
        public var dribbletPercentage: String
        public var totalTransferBNB: String
        public var totalTransferBtc: String

        public init(
            details: [String],
            dribbletPercentage: String,
            totalTransferBNB: String,
            totalTransferBtc: String
        ) {
            self.details = details
            self.dribbletPercentage = dribbletPercentage
            self.totalTransferBNB = totalTransferBNB
            self.totalTransferBtc = totalTransferBtc
        }
    }

    public struct PostSapiV1AssetDustResponse: Codable, Sendable {
        public var totalServiceCharge: String
        public var totalTransfered: String
        public var transferResult: [String]

        public init(
            totalServiceCharge: String,
            totalTransfered: String,
            transferResult: [String]
        ) {
            self.totalServiceCharge = totalServiceCharge
            self.totalTransfered = totalTransfered
            self.transferResult = transferResult
        }
    }

    public struct PostSapiV1AssetTransferResponse: Codable, Sendable {
        public var tranId: Int

        public init(
            tranId: Int
        ) {
            self.tranId = tranId
        }
    }

    public struct PostSapiV1CapitalContractConvertibleCoinsResponse: Codable, Sendable {
        public init() {}
    }

    public struct PostSapiV1CapitalDepositCreditApplyResponse: Codable, Sendable {
        public var code: String
        public var data: Bool
        public var message: String
        public var success: Bool

        public init(
            code: String,
            data: Bool,
            message: String,
            success: Bool
        ) {
            self.code = code
            self.data = data
            self.message = message
            self.success = success
        }
    }

    public struct PostSapiV1CapitalWithdrawApplyResponse: Codable, Sendable {
        public var id: String

        public init(
            id: String
        ) {
            self.id = id
        }
    }

    public struct PriceTicker: Codable, Sendable {
        public var price: String
        public var symbol: String

        public init(
            price: String,
            symbol: String
        ) {
            self.price = price
            self.symbol = symbol
        }
    }

    public typealias PriceTickerList = [PriceTicker]

    public struct SnapshotFutures: Codable, Sendable {
        public var code: Int
        public var msg: String
        public var snapshotVos: [String]

        public init(
            code: Int,
            msg: String,
            snapshotVos: [String]
        ) {
            self.code = code
            self.msg = msg
            self.snapshotVos = snapshotVos
        }
    }

    public struct SnapshotMargin: Codable, Sendable {
        public var code: Int
        public var msg: String
        public var snapshotVos: [String]

        public init(
            code: Int,
            msg: String,
            snapshotVos: [String]
        ) {
            self.code = code
            self.msg = msg
            self.snapshotVos = snapshotVos
        }
    }

    public struct SnapshotSpot: Codable, Sendable {
        public var code: Int
        public var msg: String
        public var snapshotVos: [String]

        public init(
            code: Int,
            msg: String,
            snapshotVos: [String]
        ) {
            self.code = code
            self.msg = msg
            self.snapshotVos = snapshotVos
        }
    }

    public struct Ticker: Codable, Sendable {
        public var askPrice: String
        public var askQty: String
        public var bidPrice: String
        public var bidQty: String
        public var closeTime: Int
        public var count: Int
        public var firstId: Int
        public var highPrice: String
        public var lastId: Int
        public var lastPrice: String
        public var lowPrice: String
        public var openPrice: String
        public var openTime: Int
        public var prevClosePrice: String
        public var priceChange: String
        public var priceChangePercent: String
        public var quoteVolume: String
        public var symbol: String
        public var volume: String

        public init(
            askPrice: String,
            askQty: String,
            bidPrice: String,
            bidQty: String,
            closeTime: Int,
            count: Int,
            firstId: Int,
            highPrice: String,
            lastId: Int,
            lastPrice: String,
            lowPrice: String,
            openPrice: String,
            openTime: Int,
            prevClosePrice: String,
            priceChange: String,
            priceChangePercent: String,
            quoteVolume: String,
            symbol: String,
            volume: String
        ) {
            self.askPrice = askPrice
            self.askQty = askQty
            self.bidPrice = bidPrice
            self.bidQty = bidQty
            self.closeTime = closeTime
            self.count = count
            self.firstId = firstId
            self.highPrice = highPrice
            self.lastId = lastId
            self.lastPrice = lastPrice
            self.lowPrice = lowPrice
            self.openPrice = openPrice
            self.openTime = openTime
            self.prevClosePrice = prevClosePrice
            self.priceChange = priceChange
            self.priceChangePercent = priceChangePercent
            self.quoteVolume = quoteVolume
            self.symbol = symbol
            self.volume = volume
        }
    }

    public typealias TickerList = [Ticker]

    public struct Trade: Codable, Sendable {
        public var id: Int
        public var isBestMatch: Bool
        public var isBuyerMaker: Bool
        public var price: String
        public var qty: String
        public var quoteQty: String
        public var time: Int

        public init(
            id: Int,
            isBestMatch: Bool,
            isBuyerMaker: Bool,
            price: String,
            qty: String,
            quoteQty: String,
            time: Int
        ) {
            self.id = id
            self.isBestMatch = isBestMatch
            self.isBuyerMaker = isBuyerMaker
            self.price = price
            self.qty = qty
            self.quoteQty = quoteQty
            self.time = time
        }
    }

    // MARK: - Operations (paths)

    // each operation IS a block
    public enum Operation: RequestBuildable {
        public enum Interval: String, Codable, Sendable {
            case _1s = "1s"
            case _1m = "1m"
            case _3m = "3m"
            case _5m = "5m"
            case _15m = "15m"
            case _30m = "30m"
            case _1h = "1h"
            case _2h = "2h"
            case _4h = "4h"
            case _6h = "6h"
            case _8h = "8h"
            case _12h = "12h"
            case _1d = "1d"
            case _3d = "3d"
            case _1w = "1w"
            case _1M = "1M"
        }

        public enum APIType: String, Codable, Sendable {
            case fULL = "FULL"
            case mINI = "MINI"
        }

        public enum AccountType: String, Codable, Sendable {
            case mAIN = "MAIN"
            case cARD = "CARD"
        }

        public enum NeedBtcValuation: String, Codable, Sendable {
            case `true` = "true"
            case `false` = "false"
        }

        case getApiV3AggTrades(symbol: String, fromId: Int?, startTime: Int?, endTime: Int?, limit: Int?)
        case getApiV3AvgPrice(symbol: String)
        case getApiV3Depth(symbol: String, limit: Int?)
        case getApiV3ExchangeInfo(symbol: String?, symbols: String?, permissions: String?)
        case getApiV3HistoricalTrades(symbol: String, limit: Int?, fromId: Int?)
        case getApiV3Klines(symbol: String, interval: Interval, startTime: Int?, endTime: Int?, timeZone: String?, limit: Int?)
        case getApiV3Ping
        case getApiV3Ticker(symbol: String?, symbols: String?, windowSize: String?, type: String?)
        case getApiV3Ticker24hr(symbol: String?, symbols: String?, type: APIType?)
        case getApiV3TickerBookTicker(symbol: String?, symbols: String?)
        case getApiV3TickerPrice(symbol: String?, symbols: String?)
        case getApiV3TickerTradingDay(symbol: String?, symbols: String?, timeZone: String?, type: APIType?)
        case getApiV3Time
        case getApiV3Trades(symbol: String, limit: Int?)
        case getApiV3UiKlines(symbol: String, interval: Interval, startTime: Int?, endTime: Int?, timeZone: String?, limit: Int?)
        case getSapiV1AccountApiRestrictions(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AccountApiTradingStatus(recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AccountDisableFastWithdrawSwitch(recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AccountEnableFastWithdrawSwitch(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AccountInfo(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AccountStatus(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AccountSnapshot(type: String, startTime: Int?, endTime: Int?, limit: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetAssetDetail(asset: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetAssetDividend(asset: String?, startTime: Int?, endTime: Int?, limit: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AssetConvertTransfer(clientTranId: String, asset: String, amount: Double, targetAsset: String, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetConvertTransferQueryByPage(tranId: Int?, asset: String?, startTime: Int, endTime: Int, accountType: AccountType?, current: Int?, size: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetCustodyTransferHistory(email: String, startTime: Int, endTime: Int, type: String?, asset: String, current: Int?, size: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetDribblet(accountType: String?, startTime: Int?, endTime: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AssetDust(asset: [String], accountType: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AssetDustBtc(accountType: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AssetGetFundingAsset(asset: String?, needBtcValuation: NeedBtcValuation?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetLedgerTransferCloudMiningQueryByPage(tranId: Int?, clientTranId: String?, asset: String?, startTime: Int, endTime: Int, current: Int?, size: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetTradeFee(symbol: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetTransfer(type: String, startTime: Int?, endTime: Int?, current: Int?, size: Int?, fromSymbol: String?, toSymbol: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AssetTransfer(type: String, asset: String, amount: Double, fromSymbol: String?, toSymbol: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetWalletBalance(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalConfigGetall(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalContractConvertibleCoins
        case postSapiV1CapitalContractConvertibleCoins(coin: String, enable: Bool)
        case getSapiV1CapitalDepositAddress(coin: String, network: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalDepositAddressList(coin: String, network: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1CapitalDepositCreditApply(depositId: Int?, txId: String?, subAccountId: Int?, subUserId: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalDepositHisrec(coin: String?, status: Int?, startTime: Int?, endTime: Int?, offset: Int?, limit: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalWithdrawAddressList
        case postSapiV1CapitalWithdrawApply(coin: String, withdrawOrderId: String?, network: String?, address: String, addressTag: String?, amount: Double, transactionFeeFlag: Bool?, name: String?, walletType: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalWithdrawHistory(coin: String?, withdrawOrderId: String?, status: Int?, startTime: Int?, endTime: Int?, offset: Int?, limit: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1SpotDelistSchedule(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1SystemStatus
        case postSapiV3AssetGetUserAsset(asset: String?, needBtcValuation: NeedBtcValuation?, recvWindow: Int?, timestamp: Int, signature: String)

        public var body: some RequestBuildable {
            switch self {
            case let .getApiV3AggTrades(symbol, fromId, startTime, endTime, limit):
                Method.GET
                Endpoint("api/v3/aggTrades")
                Query("symbol", symbol)
                if let fromId {
                    Query("fromId", String(fromId))
                }
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let limit {
                    Query("limit", String(limit))
                }
            case let .getApiV3AvgPrice(symbol):
                Method.GET
                Endpoint("api/v3/avgPrice")
                Query("symbol", symbol)
            case let .getApiV3Depth(symbol, limit):
                Method.GET
                Endpoint("api/v3/depth")
                Query("symbol", symbol)
                if let limit {
                    Query("limit", String(limit))
                }
            case let .getApiV3ExchangeInfo(symbol, symbols, permissions):
                Method.GET
                Endpoint("api/v3/exchangeInfo")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
                if let permissions {
                    Query("permissions", permissions)
                }
            case let .getApiV3HistoricalTrades(symbol, limit, fromId):
                Method.GET
                Endpoint("api/v3/historicalTrades")
                Query("symbol", symbol)
                if let limit {
                    Query("limit", String(limit))
                }
                if let fromId {
                    Query("fromId", String(fromId))
                }
            case let .getApiV3Klines(symbol, interval, startTime, endTime, timeZone, limit):
                Method.GET
                Endpoint("api/v3/klines")
                Query("symbol", symbol)
                Query("interval", interval.rawValue)
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let timeZone {
                    Query("timeZone", timeZone)
                }
                if let limit {
                    Query("limit", String(limit))
                }
            case .getApiV3Ping:
                Method.GET
                Endpoint("api/v3/ping")
            case let .getApiV3Ticker(symbol, symbols, windowSize, type):
                Method.GET
                Endpoint("api/v3/ticker")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
                if let windowSize {
                    Query("windowSize", windowSize)
                }
                if let type {
                    Query("type", type)
                }
            case let .getApiV3Ticker24hr(symbol, symbols, type):
                Method.GET
                Endpoint("api/v3/ticker/24hr")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
                if let type {
                    Query("type", type.rawValue)
                }
            case let .getApiV3TickerBookTicker(symbol, symbols):
                Method.GET
                Endpoint("api/v3/ticker/bookTicker")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
            case let .getApiV3TickerPrice(symbol, symbols):
                Method.GET
                Endpoint("api/v3/ticker/price")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
            case let .getApiV3TickerTradingDay(symbol, symbols, timeZone, type):
                Method.GET
                Endpoint("api/v3/ticker/tradingDay")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
                if let timeZone {
                    Query("timeZone", timeZone)
                }
                if let type {
                    Query("type", type.rawValue)
                }
            case .getApiV3Time:
                Method.GET
                Endpoint("api/v3/time")
            case let .getApiV3Trades(symbol, limit):
                Method.GET
                Endpoint("api/v3/trades")
                Query("symbol", symbol)
                if let limit {
                    Query("limit", String(limit))
                }
            case let .getApiV3UiKlines(symbol, interval, startTime, endTime, timeZone, limit):
                Method.GET
                Endpoint("api/v3/uiKlines")
                Query("symbol", symbol)
                Query("interval", interval.rawValue)
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let timeZone {
                    Query("timeZone", timeZone)
                }
                if let limit {
                    Query("limit", String(limit))
                }
            case let .getSapiV1AccountApiRestrictions(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/account/apiRestrictions")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AccountApiTradingStatus(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/account/apiTradingStatus")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AccountDisableFastWithdrawSwitch(recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/account/disableFastWithdrawSwitch")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AccountEnableFastWithdrawSwitch(recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/account/enableFastWithdrawSwitch")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AccountInfo(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/account/info")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AccountStatus(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/account/status")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AccountSnapshot(type, startTime, endTime, limit, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/accountSnapshot")
                Query("type", type)
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let limit {
                    Query("limit", String(limit))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetAssetDetail(asset, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/assetDetail")
                if let asset {
                    Query("asset", asset)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetAssetDividend(asset, startTime, endTime, limit, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/assetDividend")
                if let asset {
                    Query("asset", asset)
                }
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let limit {
                    Query("limit", String(limit))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AssetConvertTransfer(clientTranId, asset, amount, targetAsset, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/asset/convert-transfer")
                Query("clientTranId", clientTranId)
                Query("asset", asset)
                Query("amount", String(amount))
                Query("targetAsset", targetAsset)
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetConvertTransferQueryByPage(tranId, asset, startTime, endTime, accountType, current, size, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/convert-transfer/queryByPage")
                if let tranId {
                    Query("tranId", String(tranId))
                }
                if let asset {
                    Query("asset", asset)
                }
                Query("startTime", String(startTime))
                Query("endTime", String(endTime))
                if let accountType {
                    Query("accountType", accountType.rawValue)
                }
                if let current {
                    Query("current", String(current))
                }
                if let size {
                    Query("size", String(size))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetCustodyTransferHistory(email, startTime, endTime, type, asset, current, size, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/custody/transfer-history")
                Query("email", email)
                Query("startTime", String(startTime))
                Query("endTime", String(endTime))
                if let type {
                    Query("type", type)
                }
                Query("asset", asset)
                if let current {
                    Query("current", String(current))
                }
                if let size {
                    Query("size", String(size))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetDribblet(accountType, startTime, endTime, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/dribblet")
                if let accountType {
                    Query("accountType", accountType)
                }
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AssetDust(asset, accountType, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/asset/dust")
                for item in asset {
                    Query("asset", item)
                }
                if let accountType {
                    Query("accountType", accountType)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AssetDustBtc(accountType, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/asset/dust-btc")
                if let accountType {
                    Query("accountType", accountType)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AssetGetFundingAsset(asset, needBtcValuation, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/asset/get-funding-asset")
                if let asset {
                    Query("asset", asset)
                }
                if let needBtcValuation {
                    Query("needBtcValuation", needBtcValuation.rawValue)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetLedgerTransferCloudMiningQueryByPage(tranId, clientTranId, asset, startTime, endTime, current, size, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/ledger-transfer/cloud-mining/queryByPage")
                if let tranId {
                    Query("tranId", String(tranId))
                }
                if let clientTranId {
                    Query("clientTranId", clientTranId)
                }
                if let asset {
                    Query("asset", asset)
                }
                Query("startTime", String(startTime))
                Query("endTime", String(endTime))
                if let current {
                    Query("current", String(current))
                }
                if let size {
                    Query("size", String(size))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetTradeFee(symbol, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/tradeFee")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetTransfer(type, startTime, endTime, current, size, fromSymbol, toSymbol, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/transfer")
                Query("type", type)
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let current {
                    Query("current", String(current))
                }
                if let size {
                    Query("size", String(size))
                }
                if let fromSymbol {
                    Query("fromSymbol", fromSymbol)
                }
                if let toSymbol {
                    Query("toSymbol", toSymbol)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AssetTransfer(type, asset, amount, fromSymbol, toSymbol, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/asset/transfer")
                Query("type", type)
                Query("asset", asset)
                Query("amount", String(amount))
                if let fromSymbol {
                    Query("fromSymbol", fromSymbol)
                }
                if let toSymbol {
                    Query("toSymbol", toSymbol)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetWalletBalance(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/wallet/balance")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1CapitalConfigGetall(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/capital/config/getall")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case .getSapiV1CapitalContractConvertibleCoins:
                Method.GET
                Endpoint("sapi/v1/capital/contract/convertible-coins")
            case let .postSapiV1CapitalContractConvertibleCoins(coin, enable):
                Method.POST
                Endpoint("sapi/v1/capital/contract/convertible-coins")
                Query("coin", coin)
                Query("enable", String(enable))
            case let .getSapiV1CapitalDepositAddress(coin, network, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/capital/deposit/address")
                Query("coin", coin)
                if let network {
                    Query("network", network)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1CapitalDepositAddressList(coin, network, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/capital/deposit/address/list")
                Query("coin", coin)
                if let network {
                    Query("network", network)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1CapitalDepositCreditApply(depositId, txId, subAccountId, subUserId, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/capital/deposit/credit-apply")
                if let depositId {
                    Query("depositId", String(depositId))
                }
                if let txId {
                    Query("txId", txId)
                }
                if let subAccountId {
                    Query("subAccountId", String(subAccountId))
                }
                if let subUserId {
                    Query("subUserId", String(subUserId))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1CapitalDepositHisrec(coin, status, startTime, endTime, offset, limit, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/capital/deposit/hisrec")
                if let coin {
                    Query("coin", coin)
                }
                if let status {
                    Query("status", String(status))
                }
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let offset {
                    Query("offset", String(offset))
                }
                if let limit {
                    Query("limit", String(limit))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case .getSapiV1CapitalWithdrawAddressList:
                Method.GET
                Endpoint("sapi/v1/capital/withdraw/address/list")
            case let .postSapiV1CapitalWithdrawApply(coin, withdrawOrderId, network, address, addressTag, amount, transactionFeeFlag, name, walletType, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/capital/withdraw/apply")
                Query("coin", coin)
                if let withdrawOrderId {
                    Query("withdrawOrderId", withdrawOrderId)
                }
                if let network {
                    Query("network", network)
                }
                Query("address", address)
                if let addressTag {
                    Query("addressTag", addressTag)
                }
                Query("amount", String(amount))
                if let transactionFeeFlag {
                    Query("transactionFeeFlag", String(transactionFeeFlag))
                }
                if let name {
                    Query("name", name)
                }
                if let walletType {
                    Query("walletType", String(walletType))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1CapitalWithdrawHistory(coin, withdrawOrderId, status, startTime, endTime, offset, limit, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/capital/withdraw/history")
                if let coin {
                    Query("coin", coin)
                }
                if let withdrawOrderId {
                    Query("withdrawOrderId", withdrawOrderId)
                }
                if let status {
                    Query("status", String(status))
                }
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let offset {
                    Query("offset", String(offset))
                }
                if let limit {
                    Query("limit", String(limit))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1SpotDelistSchedule(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/spot/delist-schedule")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case .getSapiV1SystemStatus:
                Method.GET
                Endpoint("sapi/v1/system/status")
            case let .postSapiV3AssetGetUserAsset(asset, needBtcValuation, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v3/asset/getUserAsset")
                if let asset {
                    Query("asset", asset)
                }
                if let needBtcValuation {
                    Query("needBtcValuation", needBtcValuation.rawValue)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            }
        }
    }

    // MARK: - Responses (responses)

    public enum Responses {
        /// Statuses the spec declares below 400 for the operation.
        public static func successStatuses(_ operation: Operation) -> Set<Int> {
            [200]
        }
    }

    // MARK: - Security (securitySchemes)

    public enum Security {
        /// Scheme names the spec requires for an operation
        /// (OR-alternatives flattened into one set).
        public static func schemes(_ operation: Operation) -> Set<String> {
            switch operation {
            case .getApiV3AggTrades, .getApiV3AvgPrice, .getApiV3Depth, .getApiV3ExchangeInfo, .getApiV3HistoricalTrades,
                .getApiV3Klines, .getApiV3Ping, .getApiV3Ticker, .getApiV3Ticker24hr, .getApiV3TickerBookTicker,
                .getApiV3TickerPrice, .getApiV3TickerTradingDay, .getApiV3Time, .getApiV3Trades, .getApiV3UiKlines,
                .getSapiV1SystemStatus:
                []
            case .getSapiV1AccountApiRestrictions, .getSapiV1AccountApiTradingStatus, .postSapiV1AccountDisableFastWithdrawSwitch, .postSapiV1AccountEnableFastWithdrawSwitch, .getSapiV1AccountInfo,
                .getSapiV1AccountStatus, .getSapiV1AccountSnapshot, .getSapiV1AssetAssetDetail, .getSapiV1AssetAssetDividend, .postSapiV1AssetConvertTransfer,
                .getSapiV1AssetConvertTransferQueryByPage, .getSapiV1AssetCustodyTransferHistory, .getSapiV1AssetDribblet, .postSapiV1AssetDust, .postSapiV1AssetDustBtc,
                .postSapiV1AssetGetFundingAsset, .getSapiV1AssetLedgerTransferCloudMiningQueryByPage, .getSapiV1AssetTradeFee, .getSapiV1AssetTransfer, .postSapiV1AssetTransfer,
                .getSapiV1AssetWalletBalance, .getSapiV1CapitalConfigGetall, .getSapiV1CapitalContractConvertibleCoins, .postSapiV1CapitalContractConvertibleCoins, .getSapiV1CapitalDepositAddress,
                .getSapiV1CapitalDepositAddressList, .postSapiV1CapitalDepositCreditApply, .getSapiV1CapitalDepositHisrec, .getSapiV1CapitalWithdrawAddressList, .postSapiV1CapitalWithdrawApply,
                .getSapiV1CapitalWithdrawHistory, .getSapiV1SpotDelistSchedule, .postSapiV3AssetGetUserAsset:
                ["ApiKeyAuth"]
            }
        }

        /// Whether the spec requires `ApiKeyAuth` for the operation.
        public static func needsApiKeyAuth(_ operation: Operation) -> Bool {
            schemes(operation).contains("ApiKeyAuth")
        }

        public static func apiKeyAuth(_ value: String) -> some RequestBuildable {
            Header.custom("X-MBX-APIKEY").setValue(value)
        }
    }

    // MARK: - Authorized

    public struct MissingApiKeyAuth: Error {
        public init() {}
    }

    /// Operation + spec-required credentials as one block; apply the
    /// environment last: `.base(url).request()`.
    public static func authorized(
        _ operation: Operation,
        apiKeyAuth: String?
    ) -> some RequestBuildable {
        RequestBlock {
            operation
            if Security.needsApiKeyAuth(operation) {
                if let apiKeyAuth {
                    Security.apiKeyAuth(apiKeyAuth)
                } else {
                    RequestFailure(MissingApiKeyAuth())
                }
            }
        }
    }

    // MARK: - Client

    /// The backend as one set of typed closures — swap any field to stub.
    public struct Client: Sendable {
        public var getApiV3AggTrades: @Sendable (_ symbol: String, _ fromId: Int?, _ startTime: Int?, _ endTime: Int?, _ limit: Int?) async throws -> [AggTrade]
        public var getApiV3AvgPrice: @Sendable (_ symbol: String) async throws -> GetApiV3AvgPriceResponse
        public var getApiV3Depth: @Sendable (_ symbol: String, _ limit: Int?) async throws -> GetApiV3DepthResponse
        public var getApiV3ExchangeInfo: @Sendable (_ symbol: String?, _ symbols: String?, _ permissions: String?) async throws -> GetApiV3ExchangeInfoResponse
        public var getApiV3HistoricalTrades: @Sendable (_ symbol: String, _ limit: Int?, _ fromId: Int?) async throws -> [Trade]
        public var getApiV3Klines: @Sendable (_ symbol: String, _ interval: Operation.Interval, _ startTime: Int?, _ endTime: Int?, _ timeZone: String?, _ limit: Int?) async throws -> [[String]]
        public var getApiV3Ping: @Sendable () async throws -> GetApiV3PingResponse
        public var getApiV3Ticker: @Sendable (_ symbol: String?, _ symbols: String?, _ windowSize: String?, _ type: String?) async throws -> GetApiV3TickerResponse
        public var getApiV3Ticker24hr: @Sendable (_ symbol: String?, _ symbols: String?, _ type: Operation.APIType?) async throws -> String
        public var getApiV3TickerBookTicker: @Sendable (_ symbol: String?, _ symbols: String?) async throws -> String
        public var getApiV3TickerPrice: @Sendable (_ symbol: String?, _ symbols: String?) async throws -> String
        public var getApiV3TickerTradingDay: @Sendable (_ symbol: String?, _ symbols: String?, _ timeZone: String?, _ type: Operation.APIType?) async throws -> String
        public var getApiV3Time: @Sendable () async throws -> GetApiV3TimeResponse
        public var getApiV3Trades: @Sendable (_ symbol: String, _ limit: Int?) async throws -> [Trade]
        public var getApiV3UiKlines: @Sendable (_ symbol: String, _ interval: Operation.Interval, _ startTime: Int?, _ endTime: Int?, _ timeZone: String?, _ limit: Int?) async throws -> [[String]]
        public var getSapiV1AccountApiRestrictions: @Sendable (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AccountApiRestrictionsResponse
        public var getSapiV1AccountApiTradingStatus: @Sendable (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AccountApiTradingStatusResponse
        public var postSapiV1AccountDisableFastWithdrawSwitch: @Sendable (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AccountDisableFastWithdrawSwitchResponse
        public var postSapiV1AccountEnableFastWithdrawSwitch: @Sendable (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AccountEnableFastWithdrawSwitchResponse
        public var getSapiV1AccountInfo: @Sendable (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AccountInfoResponse
        public var getSapiV1AccountStatus: @Sendable (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AccountStatusResponse
        public var getSapiV1AccountSnapshot: @Sendable (_ type: String, _ startTime: Int?, _ endTime: Int?, _ limit: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> String
        public var getSapiV1AssetAssetDetail: @Sendable (_ asset: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetAssetDetailResponse
        public var getSapiV1AssetAssetDividend: @Sendable (_ asset: String?, _ startTime: Int?, _ endTime: Int?, _ limit: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetAssetDividendResponse
        public var postSapiV1AssetConvertTransfer: @Sendable (_ clientTranId: String, _ asset: String, _ amount: Double, _ targetAsset: String, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AssetConvertTransferResponse
        public var getSapiV1AssetConvertTransferQueryByPage: @Sendable (_ tranId: Int?, _ asset: String?, _ startTime: Int, _ endTime: Int, _ accountType: Operation.AccountType?, _ current: Int?, _ size: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetConvertTransferQueryByPageResponse
        public var getSapiV1AssetCustodyTransferHistory: @Sendable (_ email: String, _ startTime: Int, _ endTime: Int, _ type: String?, _ asset: String, _ current: Int?, _ size: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetCustodyTransferHistoryResponse
        public var getSapiV1AssetDribblet: @Sendable (_ accountType: String?, _ startTime: Int?, _ endTime: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetDribbletResponse
        public var postSapiV1AssetDust: @Sendable (_ asset: [String], _ accountType: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AssetDustResponse
        public var postSapiV1AssetDustBtc: @Sendable (_ accountType: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AssetDustBtcResponse
        public var postSapiV1AssetGetFundingAsset: @Sendable (_ asset: String?, _ needBtcValuation: Operation.NeedBtcValuation?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        public var getSapiV1AssetLedgerTransferCloudMiningQueryByPage: @Sendable (_ tranId: Int?, _ clientTranId: String?, _ asset: String?, _ startTime: Int, _ endTime: Int, _ current: Int?, _ size: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetLedgerTransferCloudMiningQueryByPageResponse
        public var getSapiV1AssetTradeFee: @Sendable (_ symbol: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        public var getSapiV1AssetTransfer: @Sendable (_ type: String, _ startTime: Int?, _ endTime: Int?, _ current: Int?, _ size: Int?, _ fromSymbol: String?, _ toSymbol: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetTransferResponse
        public var postSapiV1AssetTransfer: @Sendable (_ type: String, _ asset: String, _ amount: Double, _ fromSymbol: String?, _ toSymbol: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AssetTransferResponse
        public var getSapiV1AssetWalletBalance: @Sendable (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        public var getSapiV1CapitalConfigGetall: @Sendable (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        public var getSapiV1CapitalContractConvertibleCoins: @Sendable () async throws -> GetSapiV1CapitalContractConvertibleCoinsResponse
        public var postSapiV1CapitalContractConvertibleCoins: @Sendable (_ coin: String, _ enable: Bool) async throws -> PostSapiV1CapitalContractConvertibleCoinsResponse
        public var getSapiV1CapitalDepositAddress: @Sendable (_ coin: String, _ network: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1CapitalDepositAddressResponse
        public var getSapiV1CapitalDepositAddressList: @Sendable (_ coin: String, _ network: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        public var postSapiV1CapitalDepositCreditApply: @Sendable (_ depositId: Int?, _ txId: String?, _ subAccountId: Int?, _ subUserId: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1CapitalDepositCreditApplyResponse
        public var getSapiV1CapitalDepositHisrec: @Sendable (_ coin: String?, _ status: Int?, _ startTime: Int?, _ endTime: Int?, _ offset: Int?, _ limit: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        public var getSapiV1CapitalWithdrawAddressList: @Sendable () async throws -> [String]
        public var postSapiV1CapitalWithdrawApply: @Sendable (_ coin: String, _ withdrawOrderId: String?, _ network: String?, _ address: String, _ addressTag: String?, _ amount: Double, _ transactionFeeFlag: Bool?, _ name: String?, _ walletType: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1CapitalWithdrawApplyResponse
        public var getSapiV1CapitalWithdrawHistory: @Sendable (_ coin: String?, _ withdrawOrderId: String?, _ status: Int?, _ startTime: Int?, _ endTime: Int?, _ offset: Int?, _ limit: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        public var getSapiV1SpotDelistSchedule: @Sendable (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        public var getSapiV1SystemStatus: @Sendable () async throws -> GetSapiV1SystemStatusResponse
        public var postSapiV3AssetGetUserAsset: @Sendable (_ asset: String?, _ needBtcValuation: Operation.NeedBtcValuation?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]

        /// A whole backend that implements nothing: every field traps by name.
        /// State the operations under test by assignment, leave the rest to
        /// announce themselves. Unreachable in production — `wired` fills every
        /// field — so a trap is always a hand-built client missing one.
        public static var unimplemented: Client {
            Client(
                getApiV3AggTrades: ClosureUtilities.unimplemented("getApiV3AggTrades"),
                getApiV3AvgPrice: ClosureUtilities.unimplemented("getApiV3AvgPrice"),
                getApiV3Depth: ClosureUtilities.unimplemented("getApiV3Depth"),
                getApiV3ExchangeInfo: ClosureUtilities.unimplemented("getApiV3ExchangeInfo"),
                getApiV3HistoricalTrades: ClosureUtilities.unimplemented("getApiV3HistoricalTrades"),
                getApiV3Klines: ClosureUtilities.unimplemented("getApiV3Klines"),
                getApiV3Ping: ClosureUtilities.unimplemented("getApiV3Ping"),
                getApiV3Ticker: ClosureUtilities.unimplemented("getApiV3Ticker"),
                getApiV3Ticker24hr: ClosureUtilities.unimplemented("getApiV3Ticker24hr"),
                getApiV3TickerBookTicker: ClosureUtilities.unimplemented("getApiV3TickerBookTicker"),
                getApiV3TickerPrice: ClosureUtilities.unimplemented("getApiV3TickerPrice"),
                getApiV3TickerTradingDay: ClosureUtilities.unimplemented("getApiV3TickerTradingDay"),
                getApiV3Time: ClosureUtilities.unimplemented("getApiV3Time"),
                getApiV3Trades: ClosureUtilities.unimplemented("getApiV3Trades"),
                getApiV3UiKlines: ClosureUtilities.unimplemented("getApiV3UiKlines"),
                getSapiV1AccountApiRestrictions: ClosureUtilities.unimplemented("getSapiV1AccountApiRestrictions"),
                getSapiV1AccountApiTradingStatus: ClosureUtilities.unimplemented("getSapiV1AccountApiTradingStatus"),
                postSapiV1AccountDisableFastWithdrawSwitch: ClosureUtilities.unimplemented("postSapiV1AccountDisableFastWithdrawSwitch"),
                postSapiV1AccountEnableFastWithdrawSwitch: ClosureUtilities.unimplemented("postSapiV1AccountEnableFastWithdrawSwitch"),
                getSapiV1AccountInfo: ClosureUtilities.unimplemented("getSapiV1AccountInfo"),
                getSapiV1AccountStatus: ClosureUtilities.unimplemented("getSapiV1AccountStatus"),
                getSapiV1AccountSnapshot: ClosureUtilities.unimplemented("getSapiV1AccountSnapshot"),
                getSapiV1AssetAssetDetail: ClosureUtilities.unimplemented("getSapiV1AssetAssetDetail"),
                getSapiV1AssetAssetDividend: ClosureUtilities.unimplemented("getSapiV1AssetAssetDividend"),
                postSapiV1AssetConvertTransfer: ClosureUtilities.unimplemented("postSapiV1AssetConvertTransfer"),
                getSapiV1AssetConvertTransferQueryByPage: ClosureUtilities.unimplemented("getSapiV1AssetConvertTransferQueryByPage"),
                getSapiV1AssetCustodyTransferHistory: ClosureUtilities.unimplemented("getSapiV1AssetCustodyTransferHistory"),
                getSapiV1AssetDribblet: ClosureUtilities.unimplemented("getSapiV1AssetDribblet"),
                postSapiV1AssetDust: ClosureUtilities.unimplemented("postSapiV1AssetDust"),
                postSapiV1AssetDustBtc: ClosureUtilities.unimplemented("postSapiV1AssetDustBtc"),
                postSapiV1AssetGetFundingAsset: ClosureUtilities.unimplemented("postSapiV1AssetGetFundingAsset"),
                getSapiV1AssetLedgerTransferCloudMiningQueryByPage: ClosureUtilities.unimplemented("getSapiV1AssetLedgerTransferCloudMiningQueryByPage"),
                getSapiV1AssetTradeFee: ClosureUtilities.unimplemented("getSapiV1AssetTradeFee"),
                getSapiV1AssetTransfer: ClosureUtilities.unimplemented("getSapiV1AssetTransfer"),
                postSapiV1AssetTransfer: ClosureUtilities.unimplemented("postSapiV1AssetTransfer"),
                getSapiV1AssetWalletBalance: ClosureUtilities.unimplemented("getSapiV1AssetWalletBalance"),
                getSapiV1CapitalConfigGetall: ClosureUtilities.unimplemented("getSapiV1CapitalConfigGetall"),
                getSapiV1CapitalContractConvertibleCoins: ClosureUtilities.unimplemented("getSapiV1CapitalContractConvertibleCoins"),
                postSapiV1CapitalContractConvertibleCoins: ClosureUtilities.unimplemented("postSapiV1CapitalContractConvertibleCoins"),
                getSapiV1CapitalDepositAddress: ClosureUtilities.unimplemented("getSapiV1CapitalDepositAddress"),
                getSapiV1CapitalDepositAddressList: ClosureUtilities.unimplemented("getSapiV1CapitalDepositAddressList"),
                postSapiV1CapitalDepositCreditApply: ClosureUtilities.unimplemented("postSapiV1CapitalDepositCreditApply"),
                getSapiV1CapitalDepositHisrec: ClosureUtilities.unimplemented("getSapiV1CapitalDepositHisrec"),
                getSapiV1CapitalWithdrawAddressList: ClosureUtilities.unimplemented("getSapiV1CapitalWithdrawAddressList"),
                postSapiV1CapitalWithdrawApply: ClosureUtilities.unimplemented("postSapiV1CapitalWithdrawApply"),
                getSapiV1CapitalWithdrawHistory: ClosureUtilities.unimplemented("getSapiV1CapitalWithdrawHistory"),
                getSapiV1SpotDelistSchedule: ClosureUtilities.unimplemented("getSapiV1SpotDelistSchedule"),
                getSapiV1SystemStatus: ClosureUtilities.unimplemented("getSapiV1SystemStatus"),
                postSapiV3AssetGetUserAsset: ClosureUtilities.unimplemented("postSapiV3AssetGetUserAsset")
            )
        }

        /// Wires the typed surface over the (Operation) → Data seam. Real,
        /// mocked, or middleware-wrapped is decided entirely by the closures
        /// passed — no opinion, no defaults. The mechanics live once in the
        /// runtime's ClientBuilder; the table below is pure facts.
        public static func wired(
            execute: @escaping @Sendable (Operation) async throws -> Data,
            decoder: @escaping @Sendable (Operation) -> JSONDecoder
        ) -> Client {
            let build = ClientBuilder(execute: execute, decoder: decoder)
            return Client(
                getApiV3AggTrades: build.endpoint(Operation.getApiV3AggTrades, [AggTrade].self),
                getApiV3AvgPrice: build.endpoint(Operation.getApiV3AvgPrice, GetApiV3AvgPriceResponse.self),
                getApiV3Depth: build.endpoint(Operation.getApiV3Depth, GetApiV3DepthResponse.self),
                getApiV3ExchangeInfo: build.endpoint(Operation.getApiV3ExchangeInfo, GetApiV3ExchangeInfoResponse.self),
                getApiV3HistoricalTrades: build.endpoint(Operation.getApiV3HistoricalTrades, [Trade].self),
                getApiV3Klines: build.endpoint(Operation.getApiV3Klines, [[String]].self),
                getApiV3Ping: build.endpoint({ Operation.getApiV3Ping }, GetApiV3PingResponse.self),
                getApiV3Ticker: build.endpoint(Operation.getApiV3Ticker, GetApiV3TickerResponse.self),
                getApiV3Ticker24hr: build.endpoint(Operation.getApiV3Ticker24hr, String.self),
                getApiV3TickerBookTicker: build.endpoint(Operation.getApiV3TickerBookTicker, String.self),
                getApiV3TickerPrice: build.endpoint(Operation.getApiV3TickerPrice, String.self),
                getApiV3TickerTradingDay: build.endpoint(Operation.getApiV3TickerTradingDay, String.self),
                getApiV3Time: build.endpoint({ Operation.getApiV3Time }, GetApiV3TimeResponse.self),
                getApiV3Trades: build.endpoint(Operation.getApiV3Trades, [Trade].self),
                getApiV3UiKlines: build.endpoint(Operation.getApiV3UiKlines, [[String]].self),
                getSapiV1AccountApiRestrictions: build.endpoint(Operation.getSapiV1AccountApiRestrictions, GetSapiV1AccountApiRestrictionsResponse.self),
                getSapiV1AccountApiTradingStatus: build.endpoint(Operation.getSapiV1AccountApiTradingStatus, GetSapiV1AccountApiTradingStatusResponse.self),
                postSapiV1AccountDisableFastWithdrawSwitch: build.endpoint(Operation.postSapiV1AccountDisableFastWithdrawSwitch, PostSapiV1AccountDisableFastWithdrawSwitchResponse.self),
                postSapiV1AccountEnableFastWithdrawSwitch: build.endpoint(Operation.postSapiV1AccountEnableFastWithdrawSwitch, PostSapiV1AccountEnableFastWithdrawSwitchResponse.self),
                getSapiV1AccountInfo: build.endpoint(Operation.getSapiV1AccountInfo, GetSapiV1AccountInfoResponse.self),
                getSapiV1AccountStatus: build.endpoint(Operation.getSapiV1AccountStatus, GetSapiV1AccountStatusResponse.self),
                getSapiV1AccountSnapshot: build.endpoint(Operation.getSapiV1AccountSnapshot, String.self),
                getSapiV1AssetAssetDetail: build.endpoint(Operation.getSapiV1AssetAssetDetail, GetSapiV1AssetAssetDetailResponse.self),
                getSapiV1AssetAssetDividend: build.endpoint(Operation.getSapiV1AssetAssetDividend, GetSapiV1AssetAssetDividendResponse.self),
                postSapiV1AssetConvertTransfer: build.endpoint(Operation.postSapiV1AssetConvertTransfer, PostSapiV1AssetConvertTransferResponse.self),
                getSapiV1AssetConvertTransferQueryByPage: build.endpoint(Operation.getSapiV1AssetConvertTransferQueryByPage, GetSapiV1AssetConvertTransferQueryByPageResponse.self),
                getSapiV1AssetCustodyTransferHistory: build.endpoint(Operation.getSapiV1AssetCustodyTransferHistory, GetSapiV1AssetCustodyTransferHistoryResponse.self),
                getSapiV1AssetDribblet: build.endpoint(Operation.getSapiV1AssetDribblet, GetSapiV1AssetDribbletResponse.self),
                postSapiV1AssetDust: build.endpoint(Operation.postSapiV1AssetDust, PostSapiV1AssetDustResponse.self),
                postSapiV1AssetDustBtc: build.endpoint(Operation.postSapiV1AssetDustBtc, PostSapiV1AssetDustBtcResponse.self),
                postSapiV1AssetGetFundingAsset: build.endpoint(Operation.postSapiV1AssetGetFundingAsset, [String].self),
                getSapiV1AssetLedgerTransferCloudMiningQueryByPage: build.endpoint(Operation.getSapiV1AssetLedgerTransferCloudMiningQueryByPage, GetSapiV1AssetLedgerTransferCloudMiningQueryByPageResponse.self),
                getSapiV1AssetTradeFee: build.endpoint(Operation.getSapiV1AssetTradeFee, [String].self),
                getSapiV1AssetTransfer: build.endpoint(Operation.getSapiV1AssetTransfer, GetSapiV1AssetTransferResponse.self),
                postSapiV1AssetTransfer: build.endpoint(Operation.postSapiV1AssetTransfer, PostSapiV1AssetTransferResponse.self),
                getSapiV1AssetWalletBalance: build.endpoint(Operation.getSapiV1AssetWalletBalance, [String].self),
                getSapiV1CapitalConfigGetall: build.endpoint(Operation.getSapiV1CapitalConfigGetall, [String].self),
                getSapiV1CapitalContractConvertibleCoins: build.endpoint({ Operation.getSapiV1CapitalContractConvertibleCoins }, GetSapiV1CapitalContractConvertibleCoinsResponse.self),
                postSapiV1CapitalContractConvertibleCoins: build.endpoint(Operation.postSapiV1CapitalContractConvertibleCoins, PostSapiV1CapitalContractConvertibleCoinsResponse.self),
                getSapiV1CapitalDepositAddress: build.endpoint(Operation.getSapiV1CapitalDepositAddress, GetSapiV1CapitalDepositAddressResponse.self),
                getSapiV1CapitalDepositAddressList: build.endpoint(Operation.getSapiV1CapitalDepositAddressList, [String].self),
                postSapiV1CapitalDepositCreditApply: build.endpoint(Operation.postSapiV1CapitalDepositCreditApply, PostSapiV1CapitalDepositCreditApplyResponse.self),
                getSapiV1CapitalDepositHisrec: build.endpoint(Operation.getSapiV1CapitalDepositHisrec, [String].self),
                getSapiV1CapitalWithdrawAddressList: build.endpoint({ Operation.getSapiV1CapitalWithdrawAddressList }, [String].self),
                postSapiV1CapitalWithdrawApply: build.endpoint(Operation.postSapiV1CapitalWithdrawApply, PostSapiV1CapitalWithdrawApplyResponse.self),
                getSapiV1CapitalWithdrawHistory: build.endpoint(Operation.getSapiV1CapitalWithdrawHistory, [String].self),
                getSapiV1SpotDelistSchedule: build.endpoint(Operation.getSapiV1SpotDelistSchedule, [String].self),
                getSapiV1SystemStatus: build.endpoint({ Operation.getSapiV1SystemStatus }, GetSapiV1SystemStatusResponse.self),
                postSapiV3AssetGetUserAsset: build.endpoint(Operation.postSapiV3AssetGetUserAsset, [String].self)
            )
        }
    }

    public static let defaultBaseURL = URL(string: "https://api.binance.com")
}
