// Generated by declarative-openapi. Do not edit.

import DeclarativeOpenAPIRuntime
import DeclarativeRequests
import Foundation

// The whole backend in one closed type — sections mirror the OpenAPI document.
enum BinanceSpotAPI {
    // MARK: - Schemas (components.schemas)

    struct AggTrade: Codable {
        var M: Bool
        var t: Bool
        var a: Int
        var f: Int
        var l: Int
        var m: Bool
        var p: String
        var q: String

        enum CodingKeys: String, CodingKey {
            case M
            case t = "T"
            case a
            case f
            case l
            case m
            case p
            case q
        }
    }

    struct BookTicker: Codable {
        var askPrice: String
        var askQty: String
        var bidPrice: String
        var bidQty: String
        var symbol: String
    }

    typealias BookTickerList = [BookTicker]

    struct DayTicker: Codable {
        var closeTime: Int
        var count: Int
        var firstId: Int
        var highPrice: String
        var lastId: Int
        var lastPrice: String
        var lowPrice: String
        var openPrice: String
        var openTime: Int
        var priceChange: String
        var priceChangePercent: String
        var quoteVolume: String
        var symbol: String
        var volume: String
        var weightedAvgPrice: String
    }

    typealias DayTickerList = [DayTicker]

    struct GetApiV3AvgPriceResponse: Codable {
        var closeTime: Int
        var mins: Int
        var price: String
    }

    struct GetApiV3DepthResponse: Codable {
        var asks: [[String]]
        var bids: [[String]]
        var lastUpdateId: Int
    }

    struct GetApiV3ExchangeInfoResponse: Codable {
        var exchangeFilters: [String]
        var rateLimits: [String]
        var serverTime: Int
        var symbols: [String]
        var timezone: String
    }

    struct GetApiV3PingResponse: Codable {}

    struct GetApiV3TickerResponse: Codable {
        var closeTime: Int
        var count: Int
        var firstId: Int
        var highPrice: String
        var lastId: Int
        var lastPrice: String
        var lowPrice: String
        var openPrice: String
        var openTime: Int
        var priceChange: String
        var priceChangePercent: String
        var quoteVolume: String
        var symbol: String
        var volume: String
        var weightedAvgPrice: String
    }

    struct GetApiV3TimeResponse: Codable {
        var serverTime: Int
    }

    struct GetSapiV1AccountApiRestrictionsResponse: Codable {
        var createTime: Int
        var enableFutures: Bool
        var enableInternalTransfer: Bool
        var enableMargin: Bool
        var enablePortfolioMarginTrading: Bool? = nil
        var enableReading: Bool
        var enableSpotAndMarginTrading: Bool
        var enableVanillaOptions: Bool
        var enableWithdrawals: Bool
        var ipRestrict: Bool
        var permitsUniversalTransfer: Bool
        var tradingAuthorityExpirationTime: Int
    }

    struct GetSapiV1AccountApiTradingStatusResponse: Codable {
        var data: String
    }

    struct GetSapiV1AccountInfoResponse: Codable {
        var isFutureEnabled: Bool
        var isMarginEnabled: Bool
        var vipLevel: Int
    }

    struct GetSapiV1AccountStatusResponse: Codable {
        var data: String
    }

    struct GetSapiV1AssetAssetDetailResponse: Codable {
        var cTR: String

        enum CodingKeys: String, CodingKey {
            case cTR = "CTR"
        }
    }

    struct GetSapiV1AssetAssetDividendResponse: Codable {
        var rows: [String]
        var total: Int
    }

    struct GetSapiV1AssetConvertTransferQueryByPageResponse: Codable {
        var rows: [String]
        var total: Int
    }

    struct GetSapiV1AssetCustodyTransferHistoryResponse: Codable {
        var rows: [String]
        var total: Int
    }

    struct GetSapiV1AssetDribbletResponse: Codable {
        var total: Int
        var userAssetDribblets: [String]
    }

    struct GetSapiV1AssetLedgerTransferCloudMiningQueryByPageResponse: Codable {
        var rows: [String]
        var total: Int
    }

    struct GetSapiV1AssetTransferResponse: Codable {
        var rows: [String]
        var total: Int
    }

    struct GetSapiV1CapitalContractConvertibleCoinsResponse: Codable {
        var coins: [String]
        var convertEnabled: Bool
        var exchangeRates: String
    }

    struct GetSapiV1CapitalDepositAddressResponse: Codable {
        var address: String
        var coin: String
        var tag: String
        var url: String
    }

    struct GetSapiV1SystemStatusResponse: Codable {
        var msg: String
        var status: Int
    }

    struct PostSapiV1AccountDisableFastWithdrawSwitchResponse: Codable {}

    struct PostSapiV1AccountEnableFastWithdrawSwitchResponse: Codable {}

    struct PostSapiV1AssetConvertTransferResponse: Codable {
        var status: String
        var tranId: Int
    }

    struct PostSapiV1AssetDustBtcResponse: Codable {
        var details: [String]
        var dribbletPercentage: String
        var totalTransferBNB: String
        var totalTransferBtc: String
    }

    struct PostSapiV1AssetDustResponse: Codable {
        var totalServiceCharge: String
        var totalTransfered: String
        var transferResult: [String]
    }

    struct PostSapiV1AssetTransferResponse: Codable {
        var tranId: Int
    }

    struct PostSapiV1CapitalContractConvertibleCoinsResponse: Codable {}

    struct PostSapiV1CapitalDepositCreditApplyResponse: Codable {
        var code: String
        var data: Bool
        var message: String
        var success: Bool
    }

    struct PostSapiV1CapitalWithdrawApplyResponse: Codable {
        var id: String
    }

    struct PriceTicker: Codable {
        var price: String
        var symbol: String
    }

    typealias PriceTickerList = [PriceTicker]

    struct SnapshotFutures: Codable {
        var code: Int
        var msg: String
        var snapshotVos: [String]
    }

    struct SnapshotMargin: Codable {
        var code: Int
        var msg: String
        var snapshotVos: [String]
    }

    struct SnapshotSpot: Codable {
        var code: Int
        var msg: String
        var snapshotVos: [String]
    }

    struct Ticker: Codable {
        var askPrice: String
        var askQty: String
        var bidPrice: String
        var bidQty: String
        var closeTime: Int
        var count: Int
        var firstId: Int
        var highPrice: String
        var lastId: Int
        var lastPrice: String
        var lowPrice: String
        var openPrice: String
        var openTime: Int
        var prevClosePrice: String
        var priceChange: String
        var priceChangePercent: String
        var quoteVolume: String
        var symbol: String
        var volume: String
    }

    typealias TickerList = [Ticker]

    struct Trade: Codable {
        var id: Int
        var isBestMatch: Bool
        var isBuyerMaker: Bool
        var price: String
        var qty: String
        var quoteQty: String
        var time: Int
    }

    // MARK: - Operations (paths)

    // each operation IS a block
    enum Operation: RequestBuildable {
        enum Interval: String, Codable {
            case _1s = "1s"
            case _1m = "1m"
            case _3m = "3m"
            case _5m = "5m"
            case _15m = "15m"
            case _30m = "30m"
            case _1h = "1h"
            case _2h = "2h"
            case _4h = "4h"
            case _6h = "6h"
            case _8h = "8h"
            case _12h = "12h"
            case _1d = "1d"
            case _3d = "3d"
            case _1w = "1w"
            case _1M = "1M"
        }

        enum APIType: String, Codable {
            case fULL = "FULL"
            case mINI = "MINI"
        }

        enum AccountType: String, Codable {
            case mAIN = "MAIN"
            case cARD = "CARD"
        }

        enum NeedBtcValuation: String, Codable {
            case `true` = "true"
            case `false` = "false"
        }

        case getApiV3AggTrades(symbol: String, fromId: Int?, startTime: Int?, endTime: Int?, limit: Int?)
        case getApiV3AvgPrice(symbol: String)
        case getApiV3Depth(symbol: String, limit: Int?)
        case getApiV3ExchangeInfo(symbol: String?, symbols: String?, permissions: String?)
        case getApiV3HistoricalTrades(symbol: String, limit: Int?, fromId: Int?)
        case getApiV3Klines(symbol: String, interval: Interval, startTime: Int?, endTime: Int?, timeZone: String?, limit: Int?)
        case getApiV3Ping
        case getApiV3Ticker(symbol: String?, symbols: String?, windowSize: String?, type: String?)
        case getApiV3Ticker24hr(symbol: String?, symbols: String?, type: APIType?)
        case getApiV3TickerBookTicker(symbol: String?, symbols: String?)
        case getApiV3TickerPrice(symbol: String?, symbols: String?)
        case getApiV3TickerTradingDay(symbol: String?, symbols: String?, timeZone: String?, type: APIType?)
        case getApiV3Time
        case getApiV3Trades(symbol: String, limit: Int?)
        case getApiV3UiKlines(symbol: String, interval: Interval, startTime: Int?, endTime: Int?, timeZone: String?, limit: Int?)
        case getSapiV1AccountApiRestrictions(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AccountApiTradingStatus(recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AccountDisableFastWithdrawSwitch(recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AccountEnableFastWithdrawSwitch(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AccountInfo(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AccountStatus(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AccountSnapshot(type: String, startTime: Int?, endTime: Int?, limit: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetAssetDetail(asset: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetAssetDividend(asset: String?, startTime: Int?, endTime: Int?, limit: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AssetConvertTransfer(clientTranId: String, asset: String, amount: Double, targetAsset: String, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetConvertTransferQueryByPage(tranId: Int?, asset: String?, startTime: Int, endTime: Int, accountType: AccountType?, current: Int?, size: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetCustodyTransferHistory(email: String, startTime: Int, endTime: Int, type: String?, asset: String, current: Int?, size: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetDribblet(accountType: String?, startTime: Int?, endTime: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AssetDust(asset: [String], accountType: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AssetDustBtc(accountType: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AssetGetFundingAsset(asset: String?, needBtcValuation: NeedBtcValuation?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetLedgerTransferCloudMiningQueryByPage(tranId: Int?, clientTranId: String?, asset: String?, startTime: Int, endTime: Int, current: Int?, size: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetTradeFee(symbol: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetTransfer(type: String, startTime: Int?, endTime: Int?, current: Int?, size: Int?, fromSymbol: String?, toSymbol: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1AssetTransfer(type: String, asset: String, amount: Double, fromSymbol: String?, toSymbol: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1AssetWalletBalance(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalConfigGetall(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalContractConvertibleCoins
        case postSapiV1CapitalContractConvertibleCoins(coin: String, enable: Bool)
        case getSapiV1CapitalDepositAddress(coin: String, network: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalDepositAddressList(coin: String, network: String?, recvWindow: Int?, timestamp: Int, signature: String)
        case postSapiV1CapitalDepositCreditApply(depositId: Int?, txId: String?, subAccountId: Int?, subUserId: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalDepositHisrec(coin: String?, status: Int?, startTime: Int?, endTime: Int?, offset: Int?, limit: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalWithdrawAddressList
        case postSapiV1CapitalWithdrawApply(coin: String, withdrawOrderId: String?, network: String?, address: String, addressTag: String?, amount: Double, transactionFeeFlag: Bool?, name: String?, walletType: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1CapitalWithdrawHistory(coin: String?, withdrawOrderId: String?, status: Int?, startTime: Int?, endTime: Int?, offset: Int?, limit: Int?, recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1SpotDelistSchedule(recvWindow: Int?, timestamp: Int, signature: String)
        case getSapiV1SystemStatus
        case postSapiV3AssetGetUserAsset(asset: String?, needBtcValuation: NeedBtcValuation?, recvWindow: Int?, timestamp: Int, signature: String)

        var body: some RequestBuildable {
            switch self {
            case let .getApiV3AggTrades(symbol, fromId, startTime, endTime, limit):
                Method.GET
                Endpoint("api/v3/aggTrades")
                Query("symbol", symbol)
                if let fromId {
                    Query("fromId", String(fromId))
                }
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let limit {
                    Query("limit", String(limit))
                }
            case let .getApiV3AvgPrice(symbol):
                Method.GET
                Endpoint("api/v3/avgPrice")
                Query("symbol", symbol)
            case let .getApiV3Depth(symbol, limit):
                Method.GET
                Endpoint("api/v3/depth")
                Query("symbol", symbol)
                if let limit {
                    Query("limit", String(limit))
                }
            case let .getApiV3ExchangeInfo(symbol, symbols, permissions):
                Method.GET
                Endpoint("api/v3/exchangeInfo")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
                if let permissions {
                    Query("permissions", permissions)
                }
            case let .getApiV3HistoricalTrades(symbol, limit, fromId):
                Method.GET
                Endpoint("api/v3/historicalTrades")
                Query("symbol", symbol)
                if let limit {
                    Query("limit", String(limit))
                }
                if let fromId {
                    Query("fromId", String(fromId))
                }
            case let .getApiV3Klines(symbol, interval, startTime, endTime, timeZone, limit):
                Method.GET
                Endpoint("api/v3/klines")
                Query("symbol", symbol)
                Query("interval", interval.rawValue)
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let timeZone {
                    Query("timeZone", timeZone)
                }
                if let limit {
                    Query("limit", String(limit))
                }
            case .getApiV3Ping:
                Method.GET
                Endpoint("api/v3/ping")
            case let .getApiV3Ticker(symbol, symbols, windowSize, type):
                Method.GET
                Endpoint("api/v3/ticker")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
                if let windowSize {
                    Query("windowSize", windowSize)
                }
                if let type {
                    Query("type", type)
                }
            case let .getApiV3Ticker24hr(symbol, symbols, type):
                Method.GET
                Endpoint("api/v3/ticker/24hr")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
                if let type {
                    Query("type", type.rawValue)
                }
            case let .getApiV3TickerBookTicker(symbol, symbols):
                Method.GET
                Endpoint("api/v3/ticker/bookTicker")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
            case let .getApiV3TickerPrice(symbol, symbols):
                Method.GET
                Endpoint("api/v3/ticker/price")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
            case let .getApiV3TickerTradingDay(symbol, symbols, timeZone, type):
                Method.GET
                Endpoint("api/v3/ticker/tradingDay")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let symbols {
                    Query("symbols", symbols)
                }
                if let timeZone {
                    Query("timeZone", timeZone)
                }
                if let type {
                    Query("type", type.rawValue)
                }
            case .getApiV3Time:
                Method.GET
                Endpoint("api/v3/time")
            case let .getApiV3Trades(symbol, limit):
                Method.GET
                Endpoint("api/v3/trades")
                Query("symbol", symbol)
                if let limit {
                    Query("limit", String(limit))
                }
            case let .getApiV3UiKlines(symbol, interval, startTime, endTime, timeZone, limit):
                Method.GET
                Endpoint("api/v3/uiKlines")
                Query("symbol", symbol)
                Query("interval", interval.rawValue)
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let timeZone {
                    Query("timeZone", timeZone)
                }
                if let limit {
                    Query("limit", String(limit))
                }
            case let .getSapiV1AccountApiRestrictions(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/account/apiRestrictions")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AccountApiTradingStatus(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/account/apiTradingStatus")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AccountDisableFastWithdrawSwitch(recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/account/disableFastWithdrawSwitch")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AccountEnableFastWithdrawSwitch(recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/account/enableFastWithdrawSwitch")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AccountInfo(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/account/info")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AccountStatus(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/account/status")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AccountSnapshot(type, startTime, endTime, limit, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/accountSnapshot")
                Query("type", type)
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let limit {
                    Query("limit", String(limit))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetAssetDetail(asset, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/assetDetail")
                if let asset {
                    Query("asset", asset)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetAssetDividend(asset, startTime, endTime, limit, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/assetDividend")
                if let asset {
                    Query("asset", asset)
                }
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let limit {
                    Query("limit", String(limit))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AssetConvertTransfer(clientTranId, asset, amount, targetAsset, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/asset/convert-transfer")
                Query("clientTranId", clientTranId)
                Query("asset", asset)
                Query("amount", String(amount))
                Query("targetAsset", targetAsset)
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetConvertTransferQueryByPage(tranId, asset, startTime, endTime, accountType, current, size, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/convert-transfer/queryByPage")
                if let tranId {
                    Query("tranId", String(tranId))
                }
                if let asset {
                    Query("asset", asset)
                }
                Query("startTime", String(startTime))
                Query("endTime", String(endTime))
                if let accountType {
                    Query("accountType", accountType.rawValue)
                }
                if let current {
                    Query("current", String(current))
                }
                if let size {
                    Query("size", String(size))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetCustodyTransferHistory(email, startTime, endTime, type, asset, current, size, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/custody/transfer-history")
                Query("email", email)
                Query("startTime", String(startTime))
                Query("endTime", String(endTime))
                if let type {
                    Query("type", type)
                }
                Query("asset", asset)
                if let current {
                    Query("current", String(current))
                }
                if let size {
                    Query("size", String(size))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetDribblet(accountType, startTime, endTime, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/dribblet")
                if let accountType {
                    Query("accountType", accountType)
                }
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AssetDust(asset, accountType, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/asset/dust")
                for item in asset {
                    Query("asset", item)
                }
                if let accountType {
                    Query("accountType", accountType)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AssetDustBtc(accountType, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/asset/dust-btc")
                if let accountType {
                    Query("accountType", accountType)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AssetGetFundingAsset(asset, needBtcValuation, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/asset/get-funding-asset")
                if let asset {
                    Query("asset", asset)
                }
                if let needBtcValuation {
                    Query("needBtcValuation", needBtcValuation.rawValue)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetLedgerTransferCloudMiningQueryByPage(tranId, clientTranId, asset, startTime, endTime, current, size, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/ledger-transfer/cloud-mining/queryByPage")
                if let tranId {
                    Query("tranId", String(tranId))
                }
                if let clientTranId {
                    Query("clientTranId", clientTranId)
                }
                if let asset {
                    Query("asset", asset)
                }
                Query("startTime", String(startTime))
                Query("endTime", String(endTime))
                if let current {
                    Query("current", String(current))
                }
                if let size {
                    Query("size", String(size))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetTradeFee(symbol, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/tradeFee")
                if let symbol {
                    Query("symbol", symbol)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetTransfer(type, startTime, endTime, current, size, fromSymbol, toSymbol, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/transfer")
                Query("type", type)
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let current {
                    Query("current", String(current))
                }
                if let size {
                    Query("size", String(size))
                }
                if let fromSymbol {
                    Query("fromSymbol", fromSymbol)
                }
                if let toSymbol {
                    Query("toSymbol", toSymbol)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1AssetTransfer(type, asset, amount, fromSymbol, toSymbol, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/asset/transfer")
                Query("type", type)
                Query("asset", asset)
                Query("amount", String(amount))
                if let fromSymbol {
                    Query("fromSymbol", fromSymbol)
                }
                if let toSymbol {
                    Query("toSymbol", toSymbol)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1AssetWalletBalance(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/asset/wallet/balance")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1CapitalConfigGetall(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/capital/config/getall")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case .getSapiV1CapitalContractConvertibleCoins:
                Method.GET
                Endpoint("sapi/v1/capital/contract/convertible-coins")
            case let .postSapiV1CapitalContractConvertibleCoins(coin, enable):
                Method.POST
                Endpoint("sapi/v1/capital/contract/convertible-coins")
                Query("coin", coin)
                Query("enable", String(enable))
            case let .getSapiV1CapitalDepositAddress(coin, network, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/capital/deposit/address")
                Query("coin", coin)
                if let network {
                    Query("network", network)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1CapitalDepositAddressList(coin, network, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/capital/deposit/address/list")
                Query("coin", coin)
                if let network {
                    Query("network", network)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .postSapiV1CapitalDepositCreditApply(depositId, txId, subAccountId, subUserId, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/capital/deposit/credit-apply")
                if let depositId {
                    Query("depositId", String(depositId))
                }
                if let txId {
                    Query("txId", txId)
                }
                if let subAccountId {
                    Query("subAccountId", String(subAccountId))
                }
                if let subUserId {
                    Query("subUserId", String(subUserId))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1CapitalDepositHisrec(coin, status, startTime, endTime, offset, limit, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/capital/deposit/hisrec")
                if let coin {
                    Query("coin", coin)
                }
                if let status {
                    Query("status", String(status))
                }
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let offset {
                    Query("offset", String(offset))
                }
                if let limit {
                    Query("limit", String(limit))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case .getSapiV1CapitalWithdrawAddressList:
                Method.GET
                Endpoint("sapi/v1/capital/withdraw/address/list")
            case let .postSapiV1CapitalWithdrawApply(coin, withdrawOrderId, network, address, addressTag, amount, transactionFeeFlag, name, walletType, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v1/capital/withdraw/apply")
                Query("coin", coin)
                if let withdrawOrderId {
                    Query("withdrawOrderId", withdrawOrderId)
                }
                if let network {
                    Query("network", network)
                }
                Query("address", address)
                if let addressTag {
                    Query("addressTag", addressTag)
                }
                Query("amount", String(amount))
                if let transactionFeeFlag {
                    Query("transactionFeeFlag", String(transactionFeeFlag))
                }
                if let name {
                    Query("name", name)
                }
                if let walletType {
                    Query("walletType", String(walletType))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1CapitalWithdrawHistory(coin, withdrawOrderId, status, startTime, endTime, offset, limit, recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/capital/withdraw/history")
                if let coin {
                    Query("coin", coin)
                }
                if let withdrawOrderId {
                    Query("withdrawOrderId", withdrawOrderId)
                }
                if let status {
                    Query("status", String(status))
                }
                if let startTime {
                    Query("startTime", String(startTime))
                }
                if let endTime {
                    Query("endTime", String(endTime))
                }
                if let offset {
                    Query("offset", String(offset))
                }
                if let limit {
                    Query("limit", String(limit))
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case let .getSapiV1SpotDelistSchedule(recvWindow, timestamp, signature):
                Method.GET
                Endpoint("sapi/v1/spot/delist-schedule")
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            case .getSapiV1SystemStatus:
                Method.GET
                Endpoint("sapi/v1/system/status")
            case let .postSapiV3AssetGetUserAsset(asset, needBtcValuation, recvWindow, timestamp, signature):
                Method.POST
                Endpoint("sapi/v3/asset/getUserAsset")
                if let asset {
                    Query("asset", asset)
                }
                if let needBtcValuation {
                    Query("needBtcValuation", needBtcValuation.rawValue)
                }
                if let recvWindow {
                    Query("recvWindow", String(recvWindow))
                }
                Query("timestamp", String(timestamp))
                Query("signature", signature)
            }
        }
    }

    // MARK: - Responses (responses)

    enum Responses {
        /// Statuses the spec declares below 400 for the operation.
        static func successStatuses(_ operation: Operation) -> Set<Int> {
            [200]
        }
    }

    // MARK: - Security (securitySchemes)

    enum Security {
        /// Scheme names the spec requires for an operation
        /// (OR-alternatives flattened into one set).
        static func schemes(_ operation: Operation) -> Set<String> {
            switch operation {
            case .getApiV3AggTrades, .getApiV3AvgPrice, .getApiV3Depth, .getApiV3ExchangeInfo, .getApiV3HistoricalTrades,
                .getApiV3Klines, .getApiV3Ping, .getApiV3Ticker, .getApiV3Ticker24hr, .getApiV3TickerBookTicker,
                .getApiV3TickerPrice, .getApiV3TickerTradingDay, .getApiV3Time, .getApiV3Trades, .getApiV3UiKlines,
                .getSapiV1SystemStatus:
                []
            case .getSapiV1AccountApiRestrictions, .getSapiV1AccountApiTradingStatus, .postSapiV1AccountDisableFastWithdrawSwitch, .postSapiV1AccountEnableFastWithdrawSwitch, .getSapiV1AccountInfo,
                .getSapiV1AccountStatus, .getSapiV1AccountSnapshot, .getSapiV1AssetAssetDetail, .getSapiV1AssetAssetDividend, .postSapiV1AssetConvertTransfer,
                .getSapiV1AssetConvertTransferQueryByPage, .getSapiV1AssetCustodyTransferHistory, .getSapiV1AssetDribblet, .postSapiV1AssetDust, .postSapiV1AssetDustBtc,
                .postSapiV1AssetGetFundingAsset, .getSapiV1AssetLedgerTransferCloudMiningQueryByPage, .getSapiV1AssetTradeFee, .getSapiV1AssetTransfer, .postSapiV1AssetTransfer,
                .getSapiV1AssetWalletBalance, .getSapiV1CapitalConfigGetall, .getSapiV1CapitalContractConvertibleCoins, .postSapiV1CapitalContractConvertibleCoins, .getSapiV1CapitalDepositAddress,
                .getSapiV1CapitalDepositAddressList, .postSapiV1CapitalDepositCreditApply, .getSapiV1CapitalDepositHisrec, .getSapiV1CapitalWithdrawAddressList, .postSapiV1CapitalWithdrawApply,
                .getSapiV1CapitalWithdrawHistory, .getSapiV1SpotDelistSchedule, .postSapiV3AssetGetUserAsset:
                ["ApiKeyAuth"]
            }
        }

        /// Whether the spec requires `ApiKeyAuth` for the operation.
        static func needsApiKeyAuth(_ operation: Operation) -> Bool {
            schemes(operation).contains("ApiKeyAuth")
        }

        static func apiKeyAuth(_ value: String) -> some RequestBuildable {
            Header.custom("X-MBX-APIKEY").setValue(value)
        }
    }

    // MARK: - Authorized

    struct MissingApiKeyAuth: Error {}

    /// Operation + spec-required credentials as one block; apply the
    /// environment last: `.base(url).request()`.
    static func authorized(
        _ operation: Operation,
        apiKeyAuth: String?
    ) -> some RequestBuildable {
        RequestBlock {
            operation
            if Security.needsApiKeyAuth(operation) {
                if let apiKeyAuth {
                    Security.apiKeyAuth(apiKeyAuth)
                } else {
                    RequestFailure(MissingApiKeyAuth())
                }
            }
        }
    }

    // MARK: - Client

    /// The backend as one set of typed closures — swap any field to stub.
    struct Client {
        var getApiV3AggTrades: (_ symbol: String, _ fromId: Int?, _ startTime: Int?, _ endTime: Int?, _ limit: Int?) async throws -> [AggTrade]
        var getApiV3AvgPrice: (_ symbol: String) async throws -> GetApiV3AvgPriceResponse
        var getApiV3Depth: (_ symbol: String, _ limit: Int?) async throws -> GetApiV3DepthResponse
        var getApiV3ExchangeInfo: (_ symbol: String?, _ symbols: String?, _ permissions: String?) async throws -> GetApiV3ExchangeInfoResponse
        var getApiV3HistoricalTrades: (_ symbol: String, _ limit: Int?, _ fromId: Int?) async throws -> [Trade]
        var getApiV3Klines: (_ symbol: String, _ interval: Operation.Interval, _ startTime: Int?, _ endTime: Int?, _ timeZone: String?, _ limit: Int?) async throws -> [[String]]
        var getApiV3Ping: () async throws -> GetApiV3PingResponse
        var getApiV3Ticker: (_ symbol: String?, _ symbols: String?, _ windowSize: String?, _ type: String?) async throws -> GetApiV3TickerResponse
        var getApiV3Ticker24hr: (_ symbol: String?, _ symbols: String?, _ type: Operation.APIType?) async throws -> String
        var getApiV3TickerBookTicker: (_ symbol: String?, _ symbols: String?) async throws -> String
        var getApiV3TickerPrice: (_ symbol: String?, _ symbols: String?) async throws -> String
        var getApiV3TickerTradingDay: (_ symbol: String?, _ symbols: String?, _ timeZone: String?, _ type: Operation.APIType?) async throws -> String
        var getApiV3Time: () async throws -> GetApiV3TimeResponse
        var getApiV3Trades: (_ symbol: String, _ limit: Int?) async throws -> [Trade]
        var getApiV3UiKlines: (_ symbol: String, _ interval: Operation.Interval, _ startTime: Int?, _ endTime: Int?, _ timeZone: String?, _ limit: Int?) async throws -> [[String]]
        var getSapiV1AccountApiRestrictions: (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AccountApiRestrictionsResponse
        var getSapiV1AccountApiTradingStatus: (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AccountApiTradingStatusResponse
        var postSapiV1AccountDisableFastWithdrawSwitch: (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AccountDisableFastWithdrawSwitchResponse
        var postSapiV1AccountEnableFastWithdrawSwitch: (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AccountEnableFastWithdrawSwitchResponse
        var getSapiV1AccountInfo: (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AccountInfoResponse
        var getSapiV1AccountStatus: (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AccountStatusResponse
        var getSapiV1AccountSnapshot: (_ type: String, _ startTime: Int?, _ endTime: Int?, _ limit: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> String
        var getSapiV1AssetAssetDetail: (_ asset: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetAssetDetailResponse
        var getSapiV1AssetAssetDividend: (_ asset: String?, _ startTime: Int?, _ endTime: Int?, _ limit: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetAssetDividendResponse
        var postSapiV1AssetConvertTransfer: (_ clientTranId: String, _ asset: String, _ amount: Double, _ targetAsset: String, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AssetConvertTransferResponse
        var getSapiV1AssetConvertTransferQueryByPage: (_ tranId: Int?, _ asset: String?, _ startTime: Int, _ endTime: Int, _ accountType: Operation.AccountType?, _ current: Int?, _ size: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetConvertTransferQueryByPageResponse
        var getSapiV1AssetCustodyTransferHistory: (_ email: String, _ startTime: Int, _ endTime: Int, _ type: String?, _ asset: String, _ current: Int?, _ size: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetCustodyTransferHistoryResponse
        var getSapiV1AssetDribblet: (_ accountType: String?, _ startTime: Int?, _ endTime: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetDribbletResponse
        var postSapiV1AssetDust: (_ asset: [String], _ accountType: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AssetDustResponse
        var postSapiV1AssetDustBtc: (_ accountType: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AssetDustBtcResponse
        var postSapiV1AssetGetFundingAsset: (_ asset: String?, _ needBtcValuation: Operation.NeedBtcValuation?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        var getSapiV1AssetLedgerTransferCloudMiningQueryByPage: (_ tranId: Int?, _ clientTranId: String?, _ asset: String?, _ startTime: Int, _ endTime: Int, _ current: Int?, _ size: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetLedgerTransferCloudMiningQueryByPageResponse
        var getSapiV1AssetTradeFee: (_ symbol: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        var getSapiV1AssetTransfer: (_ type: String, _ startTime: Int?, _ endTime: Int?, _ current: Int?, _ size: Int?, _ fromSymbol: String?, _ toSymbol: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1AssetTransferResponse
        var postSapiV1AssetTransfer: (_ type: String, _ asset: String, _ amount: Double, _ fromSymbol: String?, _ toSymbol: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1AssetTransferResponse
        var getSapiV1AssetWalletBalance: (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        var getSapiV1CapitalConfigGetall: (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        var getSapiV1CapitalContractConvertibleCoins: () async throws -> GetSapiV1CapitalContractConvertibleCoinsResponse
        var postSapiV1CapitalContractConvertibleCoins: (_ coin: String, _ enable: Bool) async throws -> PostSapiV1CapitalContractConvertibleCoinsResponse
        var getSapiV1CapitalDepositAddress: (_ coin: String, _ network: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> GetSapiV1CapitalDepositAddressResponse
        var getSapiV1CapitalDepositAddressList: (_ coin: String, _ network: String?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        var postSapiV1CapitalDepositCreditApply: (_ depositId: Int?, _ txId: String?, _ subAccountId: Int?, _ subUserId: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1CapitalDepositCreditApplyResponse
        var getSapiV1CapitalDepositHisrec: (_ coin: String?, _ status: Int?, _ startTime: Int?, _ endTime: Int?, _ offset: Int?, _ limit: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        var getSapiV1CapitalWithdrawAddressList: () async throws -> [String]
        var postSapiV1CapitalWithdrawApply: (_ coin: String, _ withdrawOrderId: String?, _ network: String?, _ address: String, _ addressTag: String?, _ amount: Double, _ transactionFeeFlag: Bool?, _ name: String?, _ walletType: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> PostSapiV1CapitalWithdrawApplyResponse
        var getSapiV1CapitalWithdrawHistory: (_ coin: String?, _ withdrawOrderId: String?, _ status: Int?, _ startTime: Int?, _ endTime: Int?, _ offset: Int?, _ limit: Int?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        var getSapiV1SpotDelistSchedule: (_ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]
        var getSapiV1SystemStatus: () async throws -> GetSapiV1SystemStatusResponse
        var postSapiV3AssetGetUserAsset: (_ asset: String?, _ needBtcValuation: Operation.NeedBtcValuation?, _ recvWindow: Int?, _ timestamp: Int, _ signature: String) async throws -> [String]

        /// Wires the typed surface over the (Operation) → Data seam. Real,
        /// mocked, or middleware-wrapped is decided entirely by the closures
        /// passed — no opinion, no defaults. The mechanics live once in the
        /// runtime's ClientBuilder; the table below is pure facts.
        static func wired(
            execute: @escaping (Operation) async throws -> Data,
            decoder: @escaping (Operation) -> JSONDecoder
        ) -> Client {
            let build = ClientBuilder(execute: execute, decoder: decoder)
            return Client(
                getApiV3AggTrades: build.endpoint(Operation.getApiV3AggTrades, [AggTrade].self),
                getApiV3AvgPrice: build.endpoint(Operation.getApiV3AvgPrice, GetApiV3AvgPriceResponse.self),
                getApiV3Depth: build.endpoint(Operation.getApiV3Depth, GetApiV3DepthResponse.self),
                getApiV3ExchangeInfo: build.endpoint(Operation.getApiV3ExchangeInfo, GetApiV3ExchangeInfoResponse.self),
                getApiV3HistoricalTrades: build.endpoint(Operation.getApiV3HistoricalTrades, [Trade].self),
                getApiV3Klines: build.endpoint(Operation.getApiV3Klines, [[String]].self),
                getApiV3Ping: build.endpoint({ Operation.getApiV3Ping }, GetApiV3PingResponse.self),
                getApiV3Ticker: build.endpoint(Operation.getApiV3Ticker, GetApiV3TickerResponse.self),
                getApiV3Ticker24hr: build.endpoint(Operation.getApiV3Ticker24hr, String.self),
                getApiV3TickerBookTicker: build.endpoint(Operation.getApiV3TickerBookTicker, String.self),
                getApiV3TickerPrice: build.endpoint(Operation.getApiV3TickerPrice, String.self),
                getApiV3TickerTradingDay: build.endpoint(Operation.getApiV3TickerTradingDay, String.self),
                getApiV3Time: build.endpoint({ Operation.getApiV3Time }, GetApiV3TimeResponse.self),
                getApiV3Trades: build.endpoint(Operation.getApiV3Trades, [Trade].self),
                getApiV3UiKlines: build.endpoint(Operation.getApiV3UiKlines, [[String]].self),
                getSapiV1AccountApiRestrictions: build.endpoint(Operation.getSapiV1AccountApiRestrictions, GetSapiV1AccountApiRestrictionsResponse.self),
                getSapiV1AccountApiTradingStatus: build.endpoint(Operation.getSapiV1AccountApiTradingStatus, GetSapiV1AccountApiTradingStatusResponse.self),
                postSapiV1AccountDisableFastWithdrawSwitch: build.endpoint(Operation.postSapiV1AccountDisableFastWithdrawSwitch, PostSapiV1AccountDisableFastWithdrawSwitchResponse.self),
                postSapiV1AccountEnableFastWithdrawSwitch: build.endpoint(Operation.postSapiV1AccountEnableFastWithdrawSwitch, PostSapiV1AccountEnableFastWithdrawSwitchResponse.self),
                getSapiV1AccountInfo: build.endpoint(Operation.getSapiV1AccountInfo, GetSapiV1AccountInfoResponse.self),
                getSapiV1AccountStatus: build.endpoint(Operation.getSapiV1AccountStatus, GetSapiV1AccountStatusResponse.self),
                getSapiV1AccountSnapshot: build.endpoint(Operation.getSapiV1AccountSnapshot, String.self),
                getSapiV1AssetAssetDetail: build.endpoint(Operation.getSapiV1AssetAssetDetail, GetSapiV1AssetAssetDetailResponse.self),
                getSapiV1AssetAssetDividend: build.endpoint(Operation.getSapiV1AssetAssetDividend, GetSapiV1AssetAssetDividendResponse.self),
                postSapiV1AssetConvertTransfer: build.endpoint(Operation.postSapiV1AssetConvertTransfer, PostSapiV1AssetConvertTransferResponse.self),
                getSapiV1AssetConvertTransferQueryByPage: build.endpoint(Operation.getSapiV1AssetConvertTransferQueryByPage, GetSapiV1AssetConvertTransferQueryByPageResponse.self),
                getSapiV1AssetCustodyTransferHistory: build.endpoint(Operation.getSapiV1AssetCustodyTransferHistory, GetSapiV1AssetCustodyTransferHistoryResponse.self),
                getSapiV1AssetDribblet: build.endpoint(Operation.getSapiV1AssetDribblet, GetSapiV1AssetDribbletResponse.self),
                postSapiV1AssetDust: build.endpoint(Operation.postSapiV1AssetDust, PostSapiV1AssetDustResponse.self),
                postSapiV1AssetDustBtc: build.endpoint(Operation.postSapiV1AssetDustBtc, PostSapiV1AssetDustBtcResponse.self),
                postSapiV1AssetGetFundingAsset: build.endpoint(Operation.postSapiV1AssetGetFundingAsset, [String].self),
                getSapiV1AssetLedgerTransferCloudMiningQueryByPage: build.endpoint(Operation.getSapiV1AssetLedgerTransferCloudMiningQueryByPage, GetSapiV1AssetLedgerTransferCloudMiningQueryByPageResponse.self),
                getSapiV1AssetTradeFee: build.endpoint(Operation.getSapiV1AssetTradeFee, [String].self),
                getSapiV1AssetTransfer: build.endpoint(Operation.getSapiV1AssetTransfer, GetSapiV1AssetTransferResponse.self),
                postSapiV1AssetTransfer: build.endpoint(Operation.postSapiV1AssetTransfer, PostSapiV1AssetTransferResponse.self),
                getSapiV1AssetWalletBalance: build.endpoint(Operation.getSapiV1AssetWalletBalance, [String].self),
                getSapiV1CapitalConfigGetall: build.endpoint(Operation.getSapiV1CapitalConfigGetall, [String].self),
                getSapiV1CapitalContractConvertibleCoins: build.endpoint({ Operation.getSapiV1CapitalContractConvertibleCoins }, GetSapiV1CapitalContractConvertibleCoinsResponse.self),
                postSapiV1CapitalContractConvertibleCoins: build.endpoint(Operation.postSapiV1CapitalContractConvertibleCoins, PostSapiV1CapitalContractConvertibleCoinsResponse.self),
                getSapiV1CapitalDepositAddress: build.endpoint(Operation.getSapiV1CapitalDepositAddress, GetSapiV1CapitalDepositAddressResponse.self),
                getSapiV1CapitalDepositAddressList: build.endpoint(Operation.getSapiV1CapitalDepositAddressList, [String].self),
                postSapiV1CapitalDepositCreditApply: build.endpoint(Operation.postSapiV1CapitalDepositCreditApply, PostSapiV1CapitalDepositCreditApplyResponse.self),
                getSapiV1CapitalDepositHisrec: build.endpoint(Operation.getSapiV1CapitalDepositHisrec, [String].self),
                getSapiV1CapitalWithdrawAddressList: build.endpoint({ Operation.getSapiV1CapitalWithdrawAddressList }, [String].self),
                postSapiV1CapitalWithdrawApply: build.endpoint(Operation.postSapiV1CapitalWithdrawApply, PostSapiV1CapitalWithdrawApplyResponse.self),
                getSapiV1CapitalWithdrawHistory: build.endpoint(Operation.getSapiV1CapitalWithdrawHistory, [String].self),
                getSapiV1SpotDelistSchedule: build.endpoint(Operation.getSapiV1SpotDelistSchedule, [String].self),
                getSapiV1SystemStatus: build.endpoint({ Operation.getSapiV1SystemStatus }, GetSapiV1SystemStatusResponse.self),
                postSapiV3AssetGetUserAsset: build.endpoint(Operation.postSapiV3AssetGetUserAsset, [String].self)
            )
        }
    }

    static let defaultBaseURL = URL(string: "https://api.binance.com")
}
